### ISSUE TITLE
Image previews not displaying

### ISSUE THREAD

**Issue by bradamiller** [WPIRoboticsProjects/GRIP#101]
I created a FindLines and FilterLines operation and turned on the image previews for them. Nothing showed up in the preview area, but I did notice that the scrollbar changed, indicating that it was allocating an empty window about the right size. It did work the first time I tried it. I'll continue to play with it to see if I can find a pattern.

**Comment by JLLeitschuh** [comment]
This is a really hard bug to reproduce. I've seen it but its really rare. I'm hoping that #231 has fixed this bug.

**Comment by AustinShalit** [comment]
Do we know if #231 fixed this?

**Comment by JLLeitschuh** [comment]
I'm not sure.
I really hope so.
