### ISSUE TITLE
NullPointerException: Lost Connection to IP Webcam

### ISSUE THREAD

**Issue by nightpool** [WPIRoboticsProjects/GRIP#135]
After shutting down my IP webcam, GRIP threw a null pointer error. Ideally, GRIP would notice that it lost connection, and display the last frame it received as well as a "lost connection" notice somewhere in the UI. Ideal behavior would also include a UI control or intermittent pinging to restore connectivity when it becomes available. 

## Stack Trace:
```java
java.lang.NullPointerException
	at org.bytedeco.javacv.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:121)
	at edu.wpi.grip.core.sources.CameraSource.lambda$startVideo$23(CameraSource.java:108)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by JLLeitschuh** [comment]
Thank you!

**Comment by JLLeitschuh** [comment]
@nightpool Can you try to reproduce this problem in the v0.3.0 release?

**Comment by PaulaRudy** [comment]
Whoops, sorry about that.
