### ISSUE TITLE
Closing a camera

### ISSUE THREAD

**Issue by fauge7** [WPIRoboticsProjects/GRIP#141]
Closing a camera crashes Grip, the camera wont show up even if i put in the right values.

**Comment by ThomasJClark** [comment]
What kind of camera (webcam or IP)?  What OS?

**Comment by fauge7** [comment]
I have another issue i opened that details everything. its a usb webcam and i can acquire frames with normal opencv.

**Comment by ThomasJClark** [comment]
Ok, I see.  There seems to be an overall problem with using USB cameras on Windows, so we'll just use your first issue to track progress on it.

#142
