### ISSUE TITLE
Webcams don't work on Windows

### ISSUE THREAD

**Issue by fauge7** [WPIRoboticsProjects/GRIP#142]
Also opening a camera that does not exist causes an exception.

edit: Opening cameras on windows does not work, if the camera exists on that slot or not. The problem seems to be in the way you handle the camera class with opencv. I have used a program written with java to process an image.

## System Info:

Property Name | Property 
 ----- | -----
javafx.version | 8.0.66
java.runtime.name | Java(TM) SE Runtime Environment
java.vm.version | 25.66-b17
java.vm.vendor | Oracle Corporation
java.vm.name | Java HotSpot(TM) 64-Bit Server VM
java.runtime.version | 1.8.0_66-b17
java.awt.graphicsenv | sun.awt.Win32GraphicsEnvironment
javafx.runtime.version | 8.0.66-b17
os.name | Windows 10
os.version | 10.0
os.arch | amd64
file.encoding | Cp1252
java.vm.info | mixed mode
java.version | 1.8.0_66
sun.arch.data.model | 64
sun.cpu.endian | little

### Exception: cvCreateCameraCapture() Error: Could not create camera capture.
```java
java.io.IOException: A problem occurred trying to start the frame grabber for Webcam 1
	at edu.wpi.grip.core.sources.CameraSource.startVideo(CameraSource.java:97)
	at edu.wpi.grip.core.sources.CameraSource.<init>(CameraSource.java:68)
	at edu.wpi.grip.core.sources.CameraSource.<init>(CameraSource.java:43)
	at edu.wpi.grip.ui.pipeline.AddSourceView.lambda$null$39(AddSourceView.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bytedeco.javacv.FrameGrabber$Exception: cvCreateCameraCapture() Error: Could not create camera capture.
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:179)
	at edu.wpi.grip.core.sources.CameraSource.startVideo(CameraSource.java:95)
	... 6 more

```

**Comment by bobbysq** [comment]
Confirming.

**Comment by jojoguy10** [comment]
I'm still having issues with previewing the webcam image on Windows 10 64-bit

**Comment by JLLeitschuh** [comment]
@jojoguy10 We don't have an official release out but Webcams have been fixed for windows in the newest version.
If you want to try out the latest development build you can download it here: https://ci.appveyor.com/project/JLLeitschuh/grip/build/artifacts

**Comment by jojoguy10** [comment]
Thank you.  I'll just wait for the official release.

On Tue, Dec 8, 2015 at 9:13 AM Jonathan Leitschuh <notifications@github.com>
wrote:

> @jojoguy10 <https://github.com/jojoguy10> We don't have an official
> release out but Webcams have been fixed for windows in the newest version.
> If you want to try out the latest development build you can download it
> here: https://ci.appveyor.com/project/JLLeitschuh/grip/build/artifacts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPIRoboticsProjects/GRIP/issues/142#issuecomment-162948909>
> .
>
-- 
Joe Kelly
(503) 798-0860

**Comment by JLLeitschuh** [comment]
@jojoguy10 Its fixed in the most recent release. Give it a shot!

**Comment by jojoguy10** [comment]
I just created a new issue with the error that came up
