### ISSUE TITLE
Mask is not working properly.

### ISSUE THREAD

**Issue by PaulaRudy** [WPIRoboticsProjects/GRIP#150]
![maskerror](https://cloud.githubusercontent.com/assets/3857381/11186819/93693428-8c51-11e5-9e61-b0be97463853.jpg)

**Comment by ThomasJClark** [comment]
Could you post what steps you did to get this output (a screenshot would be fine) and the source images you used?

**Comment by PaulaRudy** [comment]
Image or mask does not seem to matter, nor does adding sequence. Except for horizontal lines.
![error5](https://cloud.githubusercontent.com/assets/3857381/11188511/37b7e00e-8c59-11e5-8831-9f6fc6ec483b.jpg)
![error4](https://cloud.githubusercontent.com/assets/3857381/11188509/37b74ffe-8c59-11e5-8fb7-50bd5fcdfc6f.jpg)
![error3](https://cloud.githubusercontent.com/assets/3857381/11188510/37b801d8-8c59-11e5-8330-8deae3529e41.jpg)
![error2](https://cloud.githubusercontent.com/assets/3857381/11188508/37b42da6-8c59-11e5-8724-a112a9ee76e3.jpg)

**Comment by ThomasJClark** [comment]
OK.  Can I see what steps you did to get this output and the source images you used?

**Comment by ThomasJClark** [comment]
It sounds like there are a lot of purely graphical defects that only happen on that one computer.  What video card do you have and which driver version are you using?

**Comment by PaulaRudy** [comment]
I have an NVIDIA GT216 (GeForce GT 220) using the Nouveau display driver from xserver-xorg-video-nouveau. I am running Ubuntu Studio using the Xfce desktop environment (version 4.12). Ubuntu version is 15.04 (vivid vervet).

**Comment by ThomasJClark** [comment]
Can you try using the proprietary nvidia driver? I just want to rule out graphics problems, since this doesn't happen in an Ubuntu vm for me

**Comment by JLLeitschuh** [comment]
@PaulaRudy Can you upload the images you used to do this test?

**Comment by ThomasJClark** [comment]
This is a non-issue.  The masks have lossy compression applied, so some pixels around the edges of the dark areas are not exactly 0.

It can be solved by using PNGs for masks.
