### ISSUE TITLE
adaptiveThreshold takes invalid enums for threshold type

### ISSUE THREAD

**Issue by PaulaRudy** [WPIRoboticsProjects/GRIP#151]
See: 
http://docs.opencv.org/3.0.0/d7/d1b/group__imgproc__misc.html#ga72b913f352e4a1b1b397736707afcde3

Should only take THRESH_BINARY and THRESH_BINARY_INV, but has dropdown items for all the threshold types.

**Comment by AustinShalit** [comment]
Closed by #628
