### ISSUE TITLE
Error Handling with Return to Normal

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#173]
Event: ErrorEvent
 - Throwable
 - Optional Message
 - Origin

Event: ErrorClearedEvent
 - Origin

ErrorWitness (final class)
 - Constructor
   - EventBus
   - Origin
 - Methods
   - error
     - throwable
     - Optional message
   - allClear
     - only posts the status when the witness's state has changed.
   - question
     - returns true if there is no error

**Comment by PaulaRudy** [comment]
Notes:
-> Fatal errors will be handled very differently than other errors
-> step errors have well defined origins

Todo:
->Figure out how errors are currently handled
->Design an error handling design
->make sure gaps are filled (go through todos in code)

note:
->can grep for error to see in code

->When do we want to throw a fatal error?
       ->when there is an exception that no one has caught?

Note: we need logging

**Comment by PaulaRudy** [comment]
>we need a "watcher":
-

**Comment by JLLeitschuh** [comment]
Closed by #175
