### ISSUE TITLE
Website no longer has javadocs posted

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#187]
This was broken by the refactor

**Comment by ThomasJClark** [comment]
The website shouldn't have the javadocs

**Comment by JLLeitschuh** [comment]
Didn't we cover this in week 2?

**Comment by ThomasJClark** [comment]
yes

**Comment by ThomasJClark** [comment]
Javadocs are not useful to have on the website

**Comment by JLLeitschuh** [comment]
If you don't find them useful that's fine.

**Comment by bradamiller** [comment]
I have agree. If it were a library with user facing APIs it would make sense to put the java docs on the web site. But where the APIs are actually internal I'm not sure that it makes sense. Other tools projects like eclipse, netbeans, etc. don't publish javadocs for the internals of their IDEs even though they can be extended with user code.

Brad




On Fri, Dec 4, 2015 at 6:27 PM -0800, "Jonathan Leitschuh" <notifications@github.com> wrote:












If you don't find them useful that's fine.
