### ISSUE TITLE
Windows(Always) Mac(Sometimes) Operations Hovered over Dissapear when GRIP Resized

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#193]
When GRIP is resized larger than its default size operations that are hovered will disappear. This happens on windows when full screened and also on OSX sometimes.
![screenshot 2015-12-06 23 29 35](https://cloud.githubusercontent.com/assets/1323708/11619119/f98d7b94-9c71-11e5-85bf-d4f965010a95.png)

**Comment by JLLeitschuh** [comment]
This may be solved by making the pallet all buttons?

**Comment by PaulaRudy** [comment]
I'm going to close this because it's a duplicate and #214 has more information in it.
