### ISSUE TITLE
Graphical errors in GUI

### ISSUE THREAD

**Issue by jojoguy10** [WPIRoboticsProjects/GRIP#214]
When the app is in fullscreen mode in Windows 10 64-bit, white boxes cover the options as I hover over them.
![screenshot_121515_061023_am](https://cloud.githubusercontent.com/assets/7492427/11812770/a4ce6ae6-a2f2-11e5-9692-1353c72a768f.jpg)
It only happens when the app is fullscreen.  The issue fixes itself after I switch to window mode.

**Comment by JLLeitschuh** [comment]
Duplicate of #193
@ThomasJClark Do you have any idea how to fix this

**Comment by PaulaRudy** [comment]
@jojoguy10 Thanks for your report! This is a known bug at this point, and we'll get working on this soon.

**Comment by PaulaRudy** [comment]
I've seen this before but it appears to not be duplicatable in Linux. @JLLeitschuh, would you like to take a stab at this? I've got a few leads: It *could* possibly be related to hardware graphics acceleration (PRISM) in JavaFx, and we could *possibly* bypass this by either disabling PRISM or by forcing JavaFX to re-render (perhaps by resizing the column width? But, of course, this is a work around and does not fix the underlying issue).

**Comment by JLLeitschuh** [comment]
This can not be reproduced in the current version of grip. Are you still seeing this bug @jojoguy10 ?

**Comment by jojoguy10** [comment]
I have note been seeing this bug in the latest version of GRIP (ver1.0.0rc4)

On Fri, Jan 8, 2016 at 9:19 PM Jonathan Leitschuh <notifications@github.com>
wrote:

> This can not be reproduced in the current version of grip. Are you still
> seeing this bug @jojoguy10 <https://github.com/jojoguy10> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPIRoboticsProjects/GRIP/issues/214#issuecomment-170199003>
> .
>
-- 
Joe Kelly
(503) 798-0860

**Comment by JLLeitschuh** [comment]
I have no idea what fixed this but cool!!
