### ISSUE TITLE
Should not be able to save a pipeline with errors (or at least shouldn't be able to deploy)

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#245]
If a step has a problem then you should not be able to deploy to the robot. This will prevent confusing "why didn't this work" problems. We should help keep users from shooting themselves in the foot.

**Comment by PaulaRudy** [comment]
I dunno about not saving- I think that would be frustrating. Maybe pop up a warning message? ("This pipeline has errors that are not addressed. Are you sure you want to deploy?" )

**Comment by PaulaRudy** [comment]
It's not really a bug though IMO.

**Comment by ThomasJClark** [comment]
A pipeline could still be work if it has some steps that aren't connected to anything.  We shouldn't stop people from deploying a perfectly working project, and we DEFINITELY should not prevent them from saving one

**Comment by PaulaRudy** [comment]
I'm with @ThomasJClark  on this one. I think maybe a popup warning for deployment might be a good idea, but I'm worried about it getting annoying.

**Comment by AustinShalit** [comment]
I am going to close this issue.  I agree that a pipeline could still work when deployed even if there are problems when it is running on the computer.
