### ISSUE TITLE
Operations feed back to previous step

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#252]
I loaded this this save file:
```xml
<grip:Pipeline>
  <sources>
    <grip:Camera>
      <property name="deviceNumber" value="0"/>
    </grip:Camera>
  </sources>
  <steps>
    <grip:Step name="resize">
      <grip:Input step="0" socket="0"/>
      <grip:Input step="0" socket="1"/>
      <grip:Input step="0" socket="2">
        <value>0.3</value>
      </grip:Input>
      <grip:Input step="0" socket="3">
        <value>0.3</value>
      </grip:Input>
      <grip:Input step="0" socket="4">
        <value>INTER_LINEAR</value>
      </grip:Input>
      <grip:Output step="0" socket="0" previewed="true"/>
    </grip:Step>
    <grip:Step name="Desaturate">
      <grip:Input step="1" socket="0"/>
      <grip:Output step="1" socket="0" previewed="true"/>
    </grip:Step>
    <grip:Step name="Find Lines">
      <grip:Input step="2" socket="0"/>
      <grip:Output step="2" socket="0" previewed="true"/>
    </grip:Step>
  </steps>
  <connections>
    <grip:Connection>
      <grip:Output step="0" socket="0" previewed="true"/>
      <grip:Input step="1" socket="0"/>
    </grip:Connection>
    <grip:Connection>
      <grip:Output step="1" socket="0" previewed="true"/>
      <grip:Input step="2" socket="0"/>
    </grip:Connection>
    <grip:Connection>
      <grip:Output source="0" socket="0" previewed="false"/>
      <grip:Input step="0" socket="0"/>
    </grip:Connection>
  </connections>
</grip:Pipeline>
```
And the pipeline looked like this:
![Pipeline Looks Wrong](https://dl.dropbox.com/s/rtld3lxv4y8b2ul/Screenshot%202016-01-04%2015.29.32.png)

Notice:
 - The steps don't have their previewed buttons toggled #253 
 - The first step that is just a simple resize is actually being desaturated as well (this issue)

The pipeline should look like this:
![How the pipeline should look](https://dl.dropbox.com/s/tdb6esdkg1pcrj4/Screenshot%202016-01-04%2015.31.06.png)

**Comment by PaulaRudy** [comment]
Seems to be associated specifically with the desaturate step. The preview windows being open is an artifact of them being open at the time the file was saved. Here's the output of the spectacular error I managed to trrigger
[GRIP.txt](https://github.com/WPIRoboticsProjects/GRIP/files/80495/GRIP.txt)

**Comment by PaulaRudy** [comment]
Tell me what you think? It's not the most elegant solution, but it works.

**Comment by JLLeitschuh** [comment]
Yea, this is not the solution we should be going with. There is a much more elegant change that should only require one line of code to be changed plus adding some ignores to some tests.

**Comment by PaulaRudy** [comment]
FYI to all interested: Apparently my solution was premature. Still working on this.

**Comment by PaulaRudy** [comment]
Are we using hash tables in the serialization process? I'm thinking this might be a hash collision that results in two references to the same memory space.

**Comment by ThomasJClark** [comment]
No, I don't think so. 

Can you check if the output of the step is actually incorrect, or only the preview? Because it could just be a bug in `PreviewsController`

**Comment by PaulaRudy** [comment]
>Can you check if the output of the step is actually incorrect, or only the preview?

Ooo...good idea!

**Comment by PaulaRudy** [comment]
Looks like the error is present within the pipeline too. The preview entries point to the right step, but both the entries in the list of previewed sockets AND the entries in the pipeline point to the same mat for both steps.
![issue252](https://cloud.githubusercontent.com/assets/3857381/12244618/9d1bd140-b872-11e5-8aed-d1bb88d4f237.jpg)

**Comment by JLLeitschuh** [comment]
That is really good information. Thanks!

**Comment by JLLeitschuh** [comment]
Thanks @PaulaRudy that the info I needed to solve the problem.
We really should have just looked at the desaturate operation and the problem would have been right there.
I thought that it was caused by some greater design problem but it wasn't it was just in the desaturate operation.
