### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by ThomasJClark** [WPIRoboticsProjects/GRIP#261]
We don't have a consistent code style defined.  It's kind of mostly been "whatever IntelliJ does by default, except when we forget to format or decide to do something different".

At some point, I'm gonna try to get the [checkstyle](https://docs.gradle.org/current/userguide/checkstyle_plugin.html) plugin integrated into the build, and we'll probably use the [Google Java Style](https://google.github.io/styleguide/javaguide.html) preset.

**Comment by JLLeitschuh** [comment]
You have to make sure whatever style sheet we use works with PMD.

**Comment by ThomasJClark** [comment]
?

**Comment by JLLeitschuh** [comment]
Codacity uses PMD under the hood.
For example, having annotations on the same line as the field declaration may break PMD.

**Comment by ThomasJClark** [comment]
What do you mean "break PMD"?  Will it not work at all?

(btw, I don't know about you, but I've basically stopped looking at codacity reports, so I wouldn't miss it)

**Comment by AustinShalit** [comment]
I am going to take a stab at setting this up.

**Comment by AustinShalit** [comment]
We have added both Checkstyle and PMD to the build.
