### ISSUE TITLE
Deploy menu item should probably be under "tools"

### ISSUE THREAD

**Issue by ThomasJClark** [WPIRoboticsProjects/GRIP#262]
I doubt we'll ever have more than one deploy option (FRC is the only one that we can do automatically since all of the FRC systems are the same).  So, "FRC Deploy" should probably be a single option under "Tools"

**Comment by bradamiller** [comment]
I can see doing deployments to other devices like the Jetson or Raspberry PI that I have in my office. I’m not sure what’s involved, but I suspect that it’s very similar to the roboRIO. That would be very cool. 

Brad

On January 4, 2016 at 5:00:49 PM, Thomas Clark (notifications@github.com) wrote:

I doubt we'll ever have more than one deploy option (FRC is the only one that we can do automatically since all of the FRC systems are the same). So, "FRC Deploy" should probably be a single option under "Tools"

**Comment by JLLeitschuh** [comment]
I agree with brad on this one.

**Comment by ThomasJClark** [comment]
Good point.  I think it's probably best under "tools", but I totally agree that it would cool to have a "deploy to raspberry pi" tool.

**Comment by JLLeitschuh** [comment]
I think a deploy menu makes more sense.

**Comment by ThomasJClark** [comment]
Why?

**Comment by AustinShalit** [comment]
Deploy menu is going to be a high use item and should be not be hidden beneath menus.  Imagine if every time you wanted to compile in an IDE you had to go hunt for the compile button...

**Comment by JLLeitschuh** [comment]
I agree with @AustinShalit on this one.

**Comment by JLLeitschuh** [comment]
Can this be closed? I think you've been outvoted on this one @ThomasJClark sorry.

**Comment by ThomasJClark** [comment]
> Can this be closed? I think you've been outvoted on this one @ThomasJClark sorry.

We currently have three ideas stated:

1. FRC Deploy should be under "tools"
2. FRC Deploy should be under "deploy"
3. FRC Deploy should be a button not in a menu

Each of these ideas was only proposed once, although I think you supported both 2 and 3

Which one are you saying wins?

**Comment by JLLeitschuh** [comment]
2

**Comment by PaulaRudy** [comment]
Has this been resolved? Can we close this?

**Comment by AustinShalit** [comment]
The master branch is currently using idea number 2.

**Comment by JLLeitschuh** [comment]
I like 2, it looks like @ThomasJClark took executive privilege and went and changed it in the network tables PR.
I vote for 2. Anyone else want to put in a vote?

**Comment by JLLeitschuh** [comment]
@ThomasJClark Can you remove the pork from #239

**Comment by ThomasJClark** [comment]
?

**Comment by JLLeitschuh** [comment]
You made the executive decision to resolve this issue the way you wanted to without us coming to a consensus.
