### ISSUE TITLE
Saved file extension

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#263]
Create a file extension that is automatically appended to the name of saved files to identify them as GRIP information.

.grip?

**Comment by JLLeitschuh** [comment]
Sure, we thought about this but the only way to do that is to append it to the end of the file that the user has given us.
We should only do this if the file doesn't already exist.

**Comment by AustinShalit** [comment]
Solved with #266

**Comment by JLLeitschuh** [comment]
Thanks for closing!
