### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by codetheweb** [WPIRoboticsProjects/GRIP#267]
Does GRIP support being run in headless mode yet from the command line? I.E. can I do something like `./grip --headless field-config.grip`?  If not, is this being developed?

**Comment by JLLeitschuh** [comment]
Currently, only somewhat.
We currently produce a JAR that can be run that is only the core library without the UI.
If you build from source you can find the file in `core/build/libs`

This will be added fully in v0.4.0 (hopefully released tomorrow).
In v0.4.0 you will be able to deploy to a remote device from within grip as well as stop and start the program.

**Comment by JLLeitschuh** [comment]
@ThomasJClark Usually, I allow the person who opened the issue to close it. It's less dismissive and allows the person to feel like they've had the opportunity to ask everything they want to.
If it sits for more than a week without comment then you close it.

**Comment by codetheweb** [comment]
@JLLeitschuh ok, thanks.
