### ISSUE TITLE
Run Core and UI in separate processes

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#268]
Since much of our code is detached using the event bus it would probably be possible to run the two in separate processes.
If we could do that it would be possible to run GRIP on a robo-rio while you had the UI running on your local computer.

This would probably work well because of how java's serialization is really easy.

**Comment by ThomasJClark** [comment]
EventBus is not designed for IPC, it's designed for use within one process

**Comment by JLLeitschuh** [comment]
I chatted with brad about this.

**Comment by SamCarlberg** [comment]
I don't think this is still relevant.

**Comment by JLLeitschuh** [comment]
I agree. It would be cool. But it would be a major re architecture.
