### ISSUE TITLE
Socket handles in sources don't fill in when connected

### ISSUE THREAD

**Issue by ThomasJClark** [WPIRoboticsProjects/GRIP#269]
This started happening after the dependency injection change was merged in.

![handle](https://cloud.githubusercontent.com/assets/3964980/12106849/a1ee7236-b331-11e5-8b76-8932f209828d.png)

**Comment by JLLeitschuh** [comment]
I don't really know how those work. Can you take a crack at that one? You fixed this one time before didn't you?

**Comment by ThomasJClark** [comment]
Ok, I'll look into it

**Comment by AustinShalit** [comment]
I am going to try to tackle this.  Give me until morning

**Comment by AustinShalit** [comment]
Solved with #285

**Comment by AustinShalit** [comment]
@ThomasJClark Can this be closed?

**Comment by ThomasJClark** [comment]
Yes.

Tip: If you put "Closes #269" in your PR message, it will automatically close this issue when it's merged
