### ISSUE TITLE
Enlarged menu dropdown

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#273]
![untitled](https://cloud.githubusercontent.com/assets/3799260/12109583/fa921996-b337-11e5-8541-ac7967c4edbe.jpg)

What causes this error is dragging the window from a large monitor to a smaller monitor.  See image below for monitor setup.  

![monitor](https://cloud.githubusercontent.com/assets/3799260/12109625/8d88b854-b338-11e5-8d5b-f9f08bdfd4ea.jpg)

For reference I am dragging the window from the middle monitor to the left.  After some testing, this is only a bug when going from large to small.  Going from small to large looks normal.

**Comment by JLLeitschuh** [comment]
It seems that our DPI check can't be a static field. But instead needs to be recalculated every time.

**Comment by ThomasJClark** [comment]
That's funny, since `DPIUtility` should return constant values on OSX, since we only do manually HiDPI adjustments on Linux.  Maybe it's weirdness in how JavaFX handles HiDPI.

Austin, is one of your screens a Retina display?

**Comment by AustinShalit** [comment]
Yes.  What I have been calling the smaller screen is a Retina display.

**Comment by AustinShalit** [comment]
I am working on this

**Comment by AustinShalit** [comment]
This appears to be a JavaFX issue: https://bugs.openjdk.java.net/browse/JDK-8087565

**Comment by AustinShalit** [comment]
Another link but they came to have fixed the issue: https://bugs.openjdk.java.net/browse/JDK-8095036

**Comment by JLLeitschuh** [comment]
This seems to be a bug in javafx and not something we can fix.

**Comment by PaulaRudy** [comment]
Nice find @AustinShalit! Thanks again for your help!

**Comment by SamCarlberg** [comment]
@AustinShalit can you test this and see if it's still happening?

**Comment by AustinShalit** [comment]
It is

**Comment by JLLeitschuh** [comment]
I think we need to make all of the DPI properties get re-computed when the monitor changes.
This means the values for DPI screens can't be set statically, they would have to be listenable properties that can be changed.

Don't know how much of a refactor this would require.

**Comment by SamCarlberg** [comment]
It's a bug in JavaFX with rendering the menu items. It's not something we can fix in GRIP.

**Comment by JLLeitschuh** [comment]
Can we trigger a re-draw when the user changes screens?

**Comment by SamCarlberg** [comment]
I don't think that would fix it. It's a problem with JavaFX not correctly updating DPI info when changing screens AFAICT

**Comment by AustinShalit** [comment]
Bug in dependency. Closing
