### ISSUE TITLE
"http://" before camera address

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#280]
Teams are required to type http:// before typing the camera ip address.  Do we expect them to open any other kind of stream?  Can we fill the "http://" for them?

**Comment by AustinShalit** [comment]
I will fix this

**Comment by ThomasJClark** [comment]
Sounds good.

**Comment by JLLeitschuh** [comment]
@nightpool Is this true?

**Comment by ThomasJClark** [comment]
Even if it's not, we just make it only fill in the `http://` if nothing else is specified, so we don't break compatibility with other things

**Comment by nightpool** [comment]
@JLLeitschuh uh can't think of any reason why not, but i mean it depends on how many kinds of protocols the underlying connection can support.

wouldn't the more elegent solution be to fill in `http://` if and only if they don't specify one?

**Comment by AustinShalit** [comment]
#284 Solves this

**Comment by AustinShalit** [comment]
thanks for closing
