### ISSUE TITLE
Document how to launch GRIP from FRC user program

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#290]
Someone needs to do this.

**Comment by AustinShalit** [comment]
```
Runtime.getRuntime().exec(params);
```

**Comment by JLLeitschuh** [comment]
This should be put in the wiki.

**Comment by AustinShalit** [comment]
Java Example:
Process grip = Runtime.getRuntime().exec(new String[]{"/usr/local/frc/JRE/bin/java", "-jar", "grip.jar", FILENAME_AS_STRING});

**Comment by ThomasJClark** [comment]
Thanks @AustinShalit, I'll put that it in the wiki before release

**Comment by JLLeitschuh** [comment]
I already did.

**Comment by PaulaRudy** [comment]
Can this be closed or does this need further attention?

**Comment by JLLeitschuh** [comment]
This document may need work but it's there.
https://github.com/WPIRoboticsProjects/GRIP/wiki/Tutorial:-Run-GRIP-from-a-CPP-or-Java-FRC-program
I think that the java one still needs to be tested fully.
I think this one is a duplicate issue: #354
When it is resolved I think we can close this one.

**Comment by AustinShalit** [comment]
I believe this has been solved.
