### ISSUE TITLE
Update settings labels

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#293]
Update the labels in settings to be formatted and named.  

Ex: Not `networkProtocol` but `Network Protocol`

![untitled](https://cloud.githubusercontent.com/assets/3799260/12160285/51587fbe-b49f-11e5-84dd-d1c9c440a4f3.jpg)

**Comment by JLLeitschuh** [comment]
Unfortunately this is how the JavaBeanConverter does it.
There might be a way to change how it works. I don't know.
@ThomasJClark this one is on you.

**Comment by ThomasJClark** [comment]
We could do it by writing a `ProjectSettingsBeanInfo` class.  I'll get to work on that now, it should be pretty simple.
