### ISSUE TITLE
Add Docs for Deployment/Network Tables

### ISSUE THREAD

**Issue by codetheweb** [WPIRoboticsProjects/GRIP#298]
I'm a little confused on how to deploy a flow to our robot, and how to view the values it publishes.  Adding something about that in the Wiki would be really helpful.

**Comment by JLLeitschuh** [comment]
Viewing the values will be through the network tables viewer built into the plugins.
As for deploying, the deploy button should be under the tools menu.
This is for [v1.0.0-rc1](https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.0.0-rc1)
I'm working on getting all of the installers uploaded right now.
