### ISSUE TITLE
Update variable for team number in deployment window

### ISSUE THREAD

**Issue by codetheweb** [WPIRoboticsProjects/GRIP#299]
When I enter our team number, then click deploy, it appears the variable for the number has not been updated by the text box going out of focus.
![grip-deployment](https://cloud.githubusercontent.com/assets/7410405/12177271/d7ad2e3e-b530-11e5-97f9-9aafed5b5b33.png)

**Comment by JLLeitschuh** [comment]
Good catch.
Workaround, hit enter.
