### ISSUE TITLE
TOO MANY LOG FILES!

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#309]
I have over 50 Grip.log files in my home directory.
We need to implement some sort of versioning so that this doesn't happen.

**Comment by PaulaRudy** [comment]
I'm not having this issue on Ubuntu. You're on apple, right?

**Comment by JLLeitschuh** [comment]
<img width="373" alt="screenshot 2016-01-08 12 06 29" src="https://cloud.githubusercontent.com/assets/1323708/12214278/701e6f86-b65b-11e5-900d-4b7336528c57.png">

Yes

**Comment by JLLeitschuh** [comment]
I have 50 of these files.

**Comment by AustinShalit** [comment]
I can confirm this is happening to me too.  I am on OS X as well.

**Comment by PaulaRudy** [comment]
Apparently these results are cumulative (info courtesy of @ThomasJClark).

**Comment by PaulaRudy** [comment]
According to the documentation and the latest code I pulled,  tell this should never be happening. @JLLeitschuh Is GRIPCoreModule() constructed more than once? That would be the only way I could see this happening.

**Comment by JLLeitschuh** [comment]
I don't think so. I think we would see the the "Config complete" more than once.

**Comment by PaulaRudy** [comment]
Looks like this is triggered by the tests somehow.... running ./gradlew check will trigger this issue for me.
