### ISSUE TITLE
Mouse Follow "Move Step"

### ISSUE THREAD

**Issue by cpapplefamily** [WPIRoboticsProjects/GRIP#325]
I just started to test the tool you created. I have been trying the different Palette tools. I could see a real use if the mouse pointer stayed over the Move Left/Right with the selected tool.

**Comment by ThomasJClark** [comment]
That's a good point, the current way you move steps is kind of cumbersome.  I think in the long term what we want to do is let you actually drag and drop steps.

**Comment by cpapplefamily** [comment]
Even better would be drag and drop. I been struggling to test the OpenCV functions on the Raspberry Pi for the past few weeks reading myself for this season. Love the live real time display.

**Comment by SamCarlberg** [comment]
Drag and drop was added a while back and didn't close this issue
