### ISSUE TITLE
Another Useful option "Minimize Operation"

### ISSUE THREAD

**Issue by cpapplefamily** [WPIRoboticsProjects/GRIP#327]
If each operation had an option to only display the used Input and Output connectors with a limited label the box could be reduced to a fraction of the size saving screen restate. 

? Is this the right place for these ideas?

**Comment by JLLeitschuh** [comment]
Yes, this is the right place for the ideas. If you want to discuss how to actually implement these ideas then join us in the [gitter chat](https://gitter.im/WPIRoboticsProjects/GRIP)

Could you provide a sketch for clarity?

**Comment by cpapplefamily** [comment]
Full Sized
![full size](https://cloud.githubusercontent.com/assets/16618289/12214524/191d5970-b65d-11e5-8494-f4d22e79f517.PNG)

**Comment by cpapplefamily** [comment]
Minimized
![minimized](https://cloud.githubusercontent.com/assets/16618289/12214527/2e30c446-b65d-11e5-958f-fba0f29aada0.png)

**Comment by cpapplefamily** [comment]
Could Stack them too then.

**Comment by JLLeitschuh** [comment]
Nice photoshop! This makes a lot more sense now!!!
