### ISSUE TITLE
Unable to Execute file GRIP.exe

### ISSUE THREAD

**Issue by jojoguy10** [WPIRoboticsProjects/GRIP#348]
One of laptops is running Windows 10 Pro 32-bit and it is coming up with this error when trying to install:

![grip error](https://cloud.githubusercontent.com/assets/7492427/12283287/e1939000-b959-11e5-9109-e577758c915e.png)

It installs fine on our other laptop that has Windows 10 Pro 64-bit

**Comment by ThomasJClark** [comment]
GRIP is built for 64 bit windows right now.

237 ran into a similar problem using a [fit-PC](http://www.fit-pc.com/web/), so I built a 32-bit build of GRIP.  I can upload it tomorrow night.

**Comment by ThomasJClark** [comment]
The 1.0.0 release has been updated to include a 32-bit windows installer (grip-1.0.0-x86.exe)

https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.0.0
