### ISSUE TITLE
Add Network Tables Source

### ISSUE THREAD

**Issue by cpapplefamily** [WPIRoboticsProjects/GRIP#363]
If there were get value from smart Dash board blocks we could dynamicly adjust filter sliders from the robot code and smart dashboard. I mentioned this in other thread and forums but needs it's own feature request.

**Comment by JLLeitschuh** [comment]
This is a feature that has been bouncing around our heads for a while.
Thanks for the suggestion.

**Comment by cpapplefamily** [comment]
ThomasJClark mention in Chief Delphi for me to add it here as a issue to be assigned. I look as if it was a thought since all the sliders appear to have input connectors.
