### ISSUE TITLE
How do you check if GRIP is already running from an FRC program?

### ISSUE THREAD

**Issue by blucoat** [WPIRoboticsProjects/GRIP#368]
I know how to start a GRIP process using the method others have suggested, but how do you know if GRIP is already running?  If the FRC program spawns a new GRIP process, then the robot code is restarted (but the RoboRIO isn't), will it create a duplicate GRIP process?

**Comment by AustinShalit** [comment]
I think this will fix the problem of spawning multiple GRIP instances.  This is untested though....
```
Process p = Runtime.getRuntime().exec(new String[]{"/usr/local/frc/JRE/bin/java", "-jar", "grip.jar", filename});
Thread closeGRIP = new Thread() {
    public void run() {
        p.destroy();
    }
};
Runtime.getRuntime().addShutdownHook(closeGRIP);
```
