### ISSUE TITLE
When loading a saved file, preview buttons are not pressed

### ISSUE THREAD

**Issue by bob80333** [WPIRoboticsProjects/GRIP#373]
The images are displayed as a preview on the top, but on the bottom the buttons are not pressed.

Image showing this below
![image](https://cloud.githubusercontent.com/assets/6364377/12370285/d6cc3fdc-bbd9-11e5-84e0-fc0e81cc7224.png)

**Comment by ThomasJClark** [comment]
Fixed by #361, expect to see this working in the next release
