### ISSUE TITLE
El Capitan crash

### ISSUE THREAD

**Issue by AlexPoulsen** [WPIRoboticsProjects/GRIP#374]
<img width="989" alt="screen shot 2016-01-16 at 11 09 20 am" src="https://cloud.githubusercontent.com/assets/9259671/12373266/b75aa7b6-bc41-11e5-8b9d-a78b1e5be2e1.png">
Crash on launch
10.11.2

**Comment by PaulaRudy** [comment]
Hello there! Could you please describe the circumstances of the crash?

**Comment by AlexPoulsen** [comment]
Opens, bounces, quits
About .5-5 seconds

**Comment by PaulaRudy** [comment]
Do you happen to have a GRIP.log file in your home folder? (If so, could you please upload it?)

**Comment by AlexPoulsen** [comment]
[GRIP.log.zip](https://github.com/WPIRoboticsProjects/GRIP/files/94979/GRIP.log.zip)

**Comment by JLLeitschuh** [comment]
Try this: 
1. Go to your Library folder on your mac (how to here: http://www.macinstruct.com/node/551)
2. Then go to `Saved Application State` and see if there is a file that has something like `edu.wpi.grip`. The file name may be longer than that.
3. Delete/Trash that file.
4. Try to open GRIP again.

**Comment by AlexPoulsen** [comment]
I've had all 3 Library folders in the sidebar for years
And nope it's not there

**Comment by JLLeitschuh** [comment]
I'm running El Capitan and I've never seen this problem.
Someone else is experiencing this problem on windows. This one has me stumped. I have no idea how to reproduce it.

What version of gcc/g++ version do you have on your machine? In your terminal type
`gcc -v` and `-g++ -v`

How tech savvy are you?
Are you willing/able to download the source code for v1.0.0 to try attaching a debugger to GRIP when you launch it?

Baring that, try reinstalling.

**Comment by AlexPoulsen** [comment]
(gcc -v)
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
(and -g++ -v)
-bash: -g++: command not found

g++ -v returns same as gcc -v

redownloaded and it still crashed

I'm not all that good with compiling source code and don't know anything about attaching a debugger to GRIP

**Comment by JacisNonsense** [comment]
Could we get some information on your system? "About My Mac" should provide everything. The OS X Version, Mac Model and CPU/GPU models should be enough for us to attempt to recreate the issue.

**Comment by AlexPoulsen** [comment]
Accidentally updated to 10.11.3, it still crashes, but this time (after redownloading), it switches my gpu from Intel Iris Pro to Nvidia GeForce GT 750M then switches back after crashing
10.11.3
Intel Iris Pro/Nvidia GeForce GT 750M
16g ram
Retina/15in/Mid-2014
4 core 2.5 GHz core i7
anything else?

**Comment by AlexPoulsen** [comment]
I don't think the GPU switched before

**Comment by JacisNonsense** [comment]
That should be it. Thank you

**Comment by JLLeitschuh** [comment]
Are you experiencing this problem with the newest release? v1.1.1

**Comment by AlexPoulsen** [comment]
yes, I am
although it stops bouncing before crashing

**Comment by JLLeitschuh** [comment]
This issue confounds me. I have no idea what is causing the problem.
I wish I had your computer in front of me to try to debug this problem.

Did you download and install the `grip-1.1.1-x64.dmg` or the `grip-1.1.1-x64.pkg` file?

**Comment by AlexPoulsen** [comment]
Just downloaded again, and it still crashes

**Comment by JLLeitschuh** [comment]
Are you willing to try building from source?
That may give us the information that we need to solve this problem for you.
Clone the repository from git and then follow the guide here:
https://github.com/WPIRoboticsProjects/GRIP/wiki/Setting-up-build-tools

Once you get it running tell us what the console outputs. There is probably some critical piece of info that we are missing.

**Comment by AustinShalit** [comment]
@AlexPoulsen Are you still having issues with the [latest version](https://github.com/WPIRoboticsProjects/GRIP/releases) of GRIP?

**Comment by AustinShalit** [comment]
@AlexPoulsen Please reopen this issue if you are still having trouble with the [latest release](https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.5.0).
