### ISSUE TITLE
Failed to Stop

### ISSUE THREAD

**Issue by Aeorx** [WPIRoboticsProjects/GRIP#376]
Froze when I tried to end my FRC deploy.

**Comment by ThomasJClark** [comment]
FYI: since there are several open issues and CD posts about problems deploying, I've opened [a new issue](377) where we can collect all of the information in one place.  If you have any information, please post it there.

**Comment by ThomasJClark** [comment]
[v1.1.0](https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.1.0) is out - this should fix most deploying problems
