### ISSUE TITLE
CameraSource Error

### ISSUE THREAD

**Issue by AaronPinto** [WPIRoboticsProjects/GRIP#390]
IP Camera 10.13.25.23 Frame Grabber Thread crashed with uncaught exception

Stack Trace
```
java.lang.NullPointerException
	at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:137)
	at edu.wpi.grip.core.sources.CameraSource.lambda$start$18(CameraSource.java:200)
	at java.lang.Thread.run(Thread.java:745)
```
I also tried using this URL as well
http://10.13.25.23/mjpg/video.mjpg

**Comment by JLLeitschuh** [comment]
Can you open that address in your web browser?

**Comment by AaronPinto** [comment]
Yes I can view the video stream in my web browser.

**Comment by JLLeitschuh** [comment]
I've opened an issue with the library author. 
https://github.com/bytedeco/javacv/issues/312
We can fix it locally in our version too.

**Comment by AaronPinto** [comment]
Great thank you! :D
