### ISSUE TITLE
Strange characters in title bars for preview

### ISSUE THREAD

**Issue by Samcfuchs** [WPIRoboticsProjects/GRIP#395]
The title bars for the preview windows have strange characters in them between words. See the screenshot below, with highlights.

I'm running Win10 on a Lenovo IdeaPad with intel i5, if that matters.
![niceletters](https://cloud.githubusercontent.com/assets/6753408/12463336/f2591dfa-bf90-11e5-8d82-fd92f5507541.PNG)

**Comment by Samcfuchs** [comment]
Reproed on an HP laptop at school, same problem.

**Comment by ThomasJClark** [comment]
I think Windows has problems loading the font we use.  I'm gonna look for a fix, possibly something to do with [this](https://github.com/cathive/fonts-roboto) library
