### ISSUE TITLE
Can't deploy to roboRIO

### ISSUE THREAD

**Issue by AaronPinto** [WPIRoboticsProjects/GRIP#396]
So I followed the tutorial on the wiki for deploying to the roboRIO but whenever I click the "Deploy" button, it always returns "Failed to connect". I have tried using the mDNS name and the IP address and I have also tried Ethernet and Wifi. I can ping the roboRIO using either the IP address or the mDNS name but I can't deploy my GRIP project to it.

I am using Windows 10 and I have all of the FRC stuff installed.

**Comment by ThomasJClark** [comment]
See #377 for deploying problems

**Comment by ThomasJClark** [comment]
[v1.1.0](https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.1.0) is out - this should fix most deploying problems
