### ISSUE TITLE
Could not verify host key with fingerprint for roboRIO

### ISSUE THREAD

**Issue by AaronPinto** [WPIRoboticsProjects/GRIP#411]
I got the new version of GRIP that was just released and the bugfixes are great. However, when I tried deploying I got a new error. 

Could not verify "ecdsa-sha2-nistp256" host key with fingerprint "b2:33:15:ba:0f:d6:2d:58:fd:05:e4:86:05:42:e5:f1" for 10.13.25.22.

If you need more information just ask.

**Comment by ThomasJClark** [comment]
What operating system?

**Comment by AaronPinto** [comment]
Windows 10

**Comment by ThomasJClark** [comment]
Fixed.  Check out the [latest release](https://github.com/WPIRoboticsProjects/GRIP/releases/latest)
