### ISSUE TITLE
"Could not load known_hosts" Error message while deploying

### ISSUE THREAD

**Issue by markebert** [WPIRoboticsProjects/GRIP#419]
When trying to deploy to the roboRio while using GRIP v1.1.0, I receive a message stating "Could not load known_hosts". I am using Windows 10 x64 with Java 8 Update 66 (64-bit) with GRIP v1.1.0 (x64).

**Comment by markebert** [comment]
![capture](https://cloud.githubusercontent.com/assets/9954598/12525340/62cb8d42-c118-11e5-96ce-ce18ab3417f5.PNG)

**Comment by ThomasJClark** [comment]
This should be fixed in [v1.1.1](https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.1.1). Feel free to re-open this issue if it still happens
