### ISSUE TITLE
VIDEOIO Error

### ISSUE THREAD

**Issue by stephenstockman** [WPIRoboticsProjects/GRIP#420]
Using a Microsoft lifecam hd3000 after the loaded no file step in deploy it states VIDEOIO ERROR:V4L/V4L2: VIDIOC_S_CROP
VIDEOIO ERROR:V4L: setting property #16 is not supported
Main start
Info:success

The grip file just has a webcam at 0; webdash board states the USB camera is at slot 0.

**Comment by ThomasJClark** [comment]
V4L prints out lots of errors depending on what webcam you're using and what the driver supports.  Is anything not actually working?

**Comment by stephenstockman** [comment]
Oh okay that's a relief, I'm still having issues with the c++ code in terms of it building but not deploying the Robot code to the bot(says success but Robot code drops). Ill attempt to get it working tmrr as I'm using a rio that has know deploy issues as our other two were being used. Thanks again for the quick replies.

**Comment by ThomasJClark** [comment]
Cool.  Definitely open a new issue tomorrow if you can't get it to work
