### ISSUE TITLE
Kinect v1 Support

### ISSUE THREAD

**Issue by JacisNonsense** [WPIRoboticsProjects/GRIP#422]
Perhaps support for the Kinect sensor would be useful for some. While the Kinect isn't detected as a webcam, the `libfreenect` library could be used to add support for the sensor. 

Both RGB and Infrared streams can be converted to images. Below are some images (taken via screenshot) from the Kinect's RGB and Infrared streams. These images can be run through GRIP to produce contours and blobs, like any other image.

![RGB](http://puu.sh/mG9fg/d3e2f8c473.png)
![Infrared](http://puu.sh/mE4FC/eddbb9b57b.jpg)

**Comment by AustinShalit** [comment]
#163 is similar

**Comment by JacisNonsense** [comment]
Closing in favour of #163
