### ISSUE TITLE
Add maintainer address to package

### ISSUE THREAD

**Issue by robobenklein** [WPIRoboticsProjects/GRIP#430]
![image](https://cloud.githubusercontent.com/assets/5423266/12538716/e533507a-c2ae-11e5-95dc-75b8b401dda4.png)

Although not absolutely needed, it would make automated and script installs much easier. Right now some install scripts will simply fail when the package does not meet quality standards.

Ubuntu Software Center at least has an option to override.

**Comment by JLLeitschuh** [comment]
Thanks.

**Comment by PaulaRudy** [comment]
Thanks for your submission!  This is a known problem right now, but it's always helpful to have an issue open for us to keep track of.

**Comment by ThomasJClark** [comment]
@paularudy, can you do this since you're on Ubuntu?

**Comment by JLLeitschuh** [comment]
Should probably just be a setting in out build.gradle
There should be an example somewhere in here: https://bitbucket.org/shemnon/javafx-gradle

**Comment by PaulaRudy** [comment]
@JLLeitschuh  the bitbucket address gives me nothing. Apparently he's stopped maintaining it :(

**Comment by JLLeitschuh** [comment]
Thats what we are using for our build.
https://bitbucket.org/shemnon/javafx-gradle/src/4695a6d1ed9e4b9248c93a877ee8374c16b9105b/samples/?at=master
There are a bunch of examples you can find in these subfolders.
