### ISSUE TITLE
Large number of errors on startup of GRIP on roboRIO

### ISSUE THREAD

**Issue by tom131313** [WPIRoboticsProjects/GRIP#433]
Large number of "normal" errors on startup of grip on roboRIO.  Can't tell if they are problems or not.    Can't tell if results will be correct or not.

Startup should be clean so real errors are obvious.

NORMAL RESTART OF ROBOT CODE FROM DRIVERSTATION - NETCONSOLE VIEW:

âž” Launching Â«'/home/lvuser/FRCUserProgram'Â»
[HAL] Starting task FRC_DriverStation...
[GRIP Test] in Constructor
[GRIP Test] Compiled file:..\src\Robot.cpp, date:Jan 25 2016, time:10:01:07, function:Robot, object address:0xef888, function:Robot::Robot(), printed at line:19
[GRIP Test] in RobotInit
[GRIP Test] fork okay, continuing with robot code.
[GRIP Test] Parent PID 3090; this robot PID 3093; JAVA GRIP in child PID=3102
Default Disabled() method... Override me!
NT: server: client CONNECTED: 169.254.6.209 port 51318
NT: server: client CONNECTED: 169.254.6.209 port 51319
Loading Dependency Injection Framework
Jan 25, 2016 3:19:48 PM java.util.logging.LogManager$RootLogger log
CONFIG: Configuration done.
Jan 25, 2016 3:19:48 PM java.util.logging.LogManager$RootLogger log
CONFIG: GRIP Version: 1.1.1
platform: /Linux/arm/
Jan 25, 2016 3:19:52 PM edu.wpi.grip.core.Main start
INFO: Loading file /home/lvuser/project.grip
VIDEOIO ERROR: V4L/V4L2: VIDIOC_S_CROP
VIDEOIO ERROR: V4L: setting property #16 is not supported
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Input must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:55 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Value must have a value to run this step.
Jan 25, 2016 3:19:57 PM edu.wpi.grip.core.Main onExceptionClearedEvent
INFO: Exception Cleared Event
Jan 25, 2016 3:19:57 PM edu.wpi.grip.core.Main onExceptionClearedEvent
INFO: Exception Cleared Event
Jan 25, 2016 3:19:57 PM edu.wpi.grip.core.Main onExceptionClearedEvent
INFO: Exception Cleared Event
NT: server: client CONNECTED: 127.0.0.1 port 34463
Jan 25, 2016 3:19:57 PM edu.wpi.grip.core.operations.networktables.NTManager lambda$new$8
INFO: NetworkTables: Dispatcher.cpp:392 client: CONNECTED to server 0.0.0.0 port 1735
Jan 25, 2016 3:19:57 PM edu.wpi.grip.core.Main onExceptionClearedEvent
INFO: Exception Cleared Event
Jan 25, 2016 3:19:57 PM edu.wpi.grip.core.Main onExceptionClearedEvent
INFO: Exception Cleared Event
Jan 25, 2016 3:19:58 PM edu.wpi.grip.core.Main start
INFO: SUCCESS! The project is running in headless mode!
NT: server: client CONNECTED: 169.254.248.235 port 52615
Jan 25, 2016 3:19:58 PM edu.wpi.grip.core.operations.networktables.NTManager lambda$new$8
INFO: NetworkTables: Dispatcher.cpp:392 client: CONNECTED to server 169.254.248.235 port 1735

**Comment by ThomasJClark** [comment]
> Large number of "normal" errors on startup of grip on roboRIO. Can't tell if they are problems or not. Can't tell if results will be correct or not.

These errors are normal.  They happen when the pipeline is loaded but the sources haven't started yet.

> Startup should be clean so real errors are obvious.

@JLLeitschuh is working on making the pipeline run synchronously when we start it instead of individual steps running in reaction to changes.  This should prevent errors like these ones.
