### ISSUE TITLE
Change exposure of camera?

### ISSUE THREAD

**Issue by Wferr** [WPIRoboticsProjects/GRIP#434]
Any way to change exposure of webcam within GRIP? Thanks!

**Comment by ThomasJClark** [comment]
For axis cameras, you can go to the address in a web browser and adjust the image settings.

For USB cameras, if the camera supports setting exposure manually, there's usually a manufacturer-specific tool that comes with the drivers.  OpenCV has some support for setting exposure and other parameters, but in my experience most cheap webcams don't work with it.
