### ISSUE TITLE
Problem deploying GRIP 

### ISSUE THREAD

**Issue by FRC3314** [WPIRoboticsProjects/GRIP#435]
![grip deploy error](https://cloud.githubusercontent.com/assets/16888989/12568400/9381b2cc-c393-11e5-9c64-f36a176ad4f1.png)

After having updated GRIP, we are unable to deploy GRIP to the roboRIO, despite it having worked before. Following the path, we clearly have the .jar file, but GRIP says that it is "not a regular file or directory." We have no idea why it isn't working.

Any help would be appreciated. Thank you.

**Comment by ThomasJClark** [comment]
It probably has something to do with the path having a space in it.  If possible, can you try making a user account without a space and trying again?

This should be easy for us to fix, but in the meantime I think that will work.

**Comment by FRC3314** [comment]
This did solve the issue. Thank you for the timely response.

**Comment by ThomasJClark** [comment]
Glad you got it to work, but I'm gonna keep this open until we fix the underlying problem
