### ISSUE TITLE
View version of GRIP from within the application

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#439]
We should add a help menu that also displays the version of grip that you are running.
Perhaps with other menu items that link to the issues and the wiki?

**Comment by PaulaRudy** [comment]
That sounds like a great idea!

**Comment by gartaud** [comment]
I second that motion. With versions of GRIP being released on a weekly basis it is difficult to keep track of which version is installed where. Thanks.

**Comment by AdamuKaapan** [comment]
I'm working on it right now.

**Comment by gartaud** [comment]
Great, thanks!
