### ISSUE TITLE
Warning icons don't show up on Windows

### ISSUE THREAD

**Issue by ThomasJClark** [WPIRoboticsProjects/GRIP#444]
This may be behind some of the mysterious "camera sources not working" problems on Windows.  The exception button uses fontawesome, which doesn't work on windows.

![icon](https://cloud.githubusercontent.com/assets/3964980/12626249/c280aa9c-c505-11e5-94d7-ff9814b1fac5.png)

This should be fixed to use a .png image ASAP so people can actually see errors.

**Comment by JLLeitschuh** [comment]
Or we could include font awesome manually so that its not downloaded from the server every time. That way it will always be present.
