### ISSUE TITLE
Some Dep. Injected Objects don't need to registered on EventBus 

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#446]
# Problem
We have a lot of objects that get created through dependency injection but really
don't need to be registered on the event bus.
This creates a memory leak because references to objects that don't need to be registered will stick around.

The list of problem classes include but is not limited to 

- [ ] Image Sources
- [ ] All factories
- [ ] Steps

# Proposal
1. Add an annotation like `@NoRegister` to prevent objects from being registered automatically.
  - Pros
    - Allows you to manage the registration of an object manually
  - Cons
    - May be confusing if you can't figure out why your object's subscribers aren't working if you add them later.
2. Only register objects that actually have a `@Subscribe` method
  - Pros
    - We only register objects that actually care about the event bus.
  - Cons 
    - You can't manually control the registering of objects if timing matters.

@ThomasJClark and @PaulaRudy your opinion on which route would make more sense would be helpful.

**Comment by ThomasJClark** [comment]
> This creates a memory leak because references to objects that don't need to be registered will stick around.

I literally don't believe this is true.  Why would Guava hold references to these objects?
