### ISSUE TITLE
Network Tables and GRIP on Raspberry Pi

### ISSUE THREAD

**Issue by KevinMackenzie** [WPIRoboticsProjects/GRIP#457]
I am currently attempting to run GRIP on the Raspberry Pi 2 model B+.  I followed the wiki instructions, and I finished them with little issues, however when I start grip (either from ssh or the grip gui on windows) I get as slew of errors.

http://pastebin.com/YPnd6rVf

The one that catches my eye, is the "/tmp/libNetworkTablesJNI8490534770071707578.so" part.  I went to that directory, and saw there was nothing there.  On the roborio, there are those files.  The number after "JNI" is completely random, so I can't just copy/paste them.  What do I need to do to get these files in this location? 

It appears the network tables are not setting properly.

**Comment by ThomasJClark** [comment]
GRIP isn't supported officially on the Raspberry Pi.  Check out #366 for community-lead support for this.
