### ISSUE TITLE
Publishing network tables from Kangaroo to RoboRIO

### ISSUE THREAD

**Issue by FRC3314** [WPIRoboticsProjects/GRIP#459]
![image](https://cloud.githubusercontent.com/assets/16888989/12698771/b8364c02-c773-11e5-9f3f-95eb4433aa51.png)
How would you go about doing this? We've set the Kangaroo to publish the network tables to the RIO, but it doesn't seem to be receiving them. When we check the network tables, there's no data. We're connected to the RIO by wifi, if that matters.

**Comment by ThomasJClark** [comment]
Are you checking the values using a robot program, or using OutlineViewer?  If it's OutlineViewer, are you in server or client mode?

Are you sure the kangaroo can connect to the rio?  Can you ping it?

**Comment by FRC3314** [comment]
We're trying to get the Kangaroo to send the values to the rio, and then we're viewing them on a laptop using OutlineViewer in client mode. We can see the values when we run GRIP off the laptop, but not when we run it off the Kangaroo. 

The Kangaroo seems to be connecting to the rio, as we can ping the rio from the Kangaroo.

**Comment by bradamiller** [comment]
I've been running GRIP on a kangaroo connected to RoboRIO and it's been working for me. Can you make sure that you have the networking set up correctly on the kangaroo. Maybe you can verify that you can ping the roboRIO from the kangaroo when it's connected to a monitor. In fact if you're running wirelessly then you can have the kangaroo off the robot and keep it next to a monitor communicating to the robot access point. Then you can keep a keyboard and mouse connected to it for easier testing.

**Comment by FRC3314** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/16888989/12704461/8ee0126e-c829-11e5-8e8e-2a26872cd31e.png)

We have successfully pinged the Roborio from the kangaroo. Our current setup is the kangaroo connected wirelessly to the robot with the monitor, keyboard, and mouse connected to the kangaroo.

**Comment by ThomasJClark** [comment]
That's not the same address you have set as your "NetworkTables server address".

Try changing it to 10.33.14.58, and try pinging roborio-3314-frc.local.

**Comment by FRC3314** [comment]
![untitled3](https://cloud.githubusercontent.com/assets/16888989/12704744/5a4eb284-c82f-11e5-88ad-50addb29874d.png)
It seems we are unable to find the rio. We changed the network tables server address to 10.33.14.58

**Comment by bradamiller** [comment]
You could always put the actual robot IP address into the Kangaroo instead of relying on the team number and the mDNS lookup, then the network tables client should connect.

**Comment by ThomasJClark** [comment]
Are you sure the roboRIO's address is 10.33.14.58?  Usually it's something like 10.33.14.2.

**Comment by FRC3314** [comment]
We re-changed the networktables server address to 10.33.14.58 and it seems to be working now. We don't know why it began it work now seeing as we have already done this, but it is now working. Thanks
