### ISSUE TITLE
Input sockets can have multiple connections

### ISSUE THREAD

**Issue by ThomasJClark** [WPIRoboticsProjects/GRIP#46]
Currently it is possible to connect multiple things to an input of a step.  This shouldn't be allowed - it makes the value of the socket ambiguous and dependent on the timing of the events in the application.  Instead, when the user tries to make a connection to an input socket that is already connected to something, we could either not allow it, or just remove the old connection.

![steps](https://cloud.githubusercontent.com/assets/3964980/10422232/79ff7a66-7085-11e5-8237-57492c5947ca.png)

**Comment by JLLeitschuh** [comment]
Do we want to support this for sockets that take MatVectors?
