### ISSUE TITLE
getNumberArray Method not Working

### ISSUE THREAD

**Issue by TitaniumKnightsFRC** [WPIRoboticsProjects/GRIP#474]
`for (double area : grip.getNumberArray("targets/area", new double[0])) {
            System.out.println("Got contour with area=" + area);
        }`

"The method getNumberArray(String, double[]) is undefined for the type NetworkTable."

**Comment by AustinShalit** [comment]
Can you please post more code?  That example should work.

**Comment by ThomasJClark** [comment]
Is this an old version of NetworkTables?  GRIP uses the v3 protocol, which is new in 2016.
