### ISSUE TITLE
Units of contour report

### ISSUE THREAD

**Issue by chackotaco** [WPIRoboticsProjects/GRIP#487]
#First of all, I want to say thank you to all of you who give up your time to contribute to GRIP. It's been extremely useful for many teams!

I had a question about the "units" of the contour report:
centerX and centerY gives the measure of the distance of the contour from the top left corner. Are these "distances" in pixels? I noticed that lowering the resolution of Axis camera did lower the average centerX and centerY values. Also, are the centerX and centerY measurements affected by the GRIP 'resize' operation? 

Thanks!

**Comment by ThomasJClark** [comment]
Yes, these are in pixels.  If you use a resize operation, the numbers will be smaller, as there are less pixels from there to the top of the screen.

If you think you might resize the image and you want to future-proof your robot program, you can publish the resolution to NetworkTables.

![publish](https://cloud.githubusercontent.com/assets/3964980/12871043/1c16f20c-cd33-11e5-8b37-c7bc164ea805.png)
