### ISSUE TITLE
GRIP should take command line options in GUI mode

### ISSUE THREAD

**Issue by skypanther** [WPIRoboticsProjects/GRIP#492]
We're attempting to run grip on our driver's station. We have the basics working, but we have to open the .grip file from the menus every time we start grip. I cannot find documentation on how to automatically load the file and our attempts to guess at command-line parameters that might do so have not worked.

**Comment by ThomasJClark** [comment]
There are no command line parameters to open a file with the GUI currently.

You could run it in headless mode by running `java -jar core-1.2.0-all.jar [file.grip]`, or you could also use the keyboard shortcut (Ctrl+O) for convenience.  An optional command line parameter sounds like a good idea though for the next release.

**Comment by skypanther** [comment]
Thanks. We'll try the `java -jar` technique. Since you've tagged this as an enhancement, I'll leave this issue open. Feel free to close if you'd rather track the idea in a different way.
