### ISSUE TITLE
Feature Request: Be able to start and stop pipeline from within program

### ISSUE THREAD

**Issue by rlee287** [WPIRoboticsProjects/GRIP#501]
Being able to start and stop the pipeline from inside an FRC program would help the program save resources and run GRIP only when actually needed.

**Comment by JLLeitschuh** [comment]
This is not a planned feature. You could stop and start the running grip process using your FRC user program.

**Comment by ThomasJClark** [comment]
> This is not a planned feature. You could stop and start the running grip process using your FRC user program.

GRIP takes a couple seconds to start up though, and we already have starting and stopping implemented.  We could very easily make it so you can, say, set a networktables key like "GRIP/run" to true or false to start and stop the pipeline
