### ISSUE TITLE
Cannot open IP Cameras in GRIP

### ISSUE THREAD

**Issue by cyberx696** [WPIRoboticsProjects/GRIP#503]
After building the latest source code, I still encounter the issue where the IP camera throws an exception and (in my case) don't even start. I've tried them in the v1.2 release too, but the same error occurs.

GRIP.log.txt

TECHNICAL DETAILS:
OS: Windows 7
Release: Stable 1.2
Camera: Axis M1013, Panasonic VP104
Setup: Axis camera connected via ethernet to RoboRIO. Laptop running GRIP connected over Wifi to RoboRIO.

The first one (Axis M1013) crashed with a camera source error where it failed to grab the image. I tested this URL (`http://10.6.96.10/cgi-bin/mjpeg`) in a browser but it failed in GRIP. The error is below.
```
edu.wpi.grip.core.sources.CameraSource$1 run
WARNING: Failed to grab image
org.bytedeco.javacv.FrameGrabber$Exception: The camera stream ended unexpectedly
at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:137)
at edu.wpi.grip.core.sources.CameraSource$1.run(CameraSource.java:227)
at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: The camera stream ended unexpectedly
at edu.wpi.grip.core.sources.IPCameraFrameGrabber.readImage(IPCameraFrameGrabber.java:177)
at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:130)
... 4 more
```
The second camera I tested (a Panasonic V104) also failed to start. I tested three different URLs (`http://10.6.96.20/axis-cgi/mjpg/video.cgi?camera=1&resolution=320x240`, `http://10.6.96.20/mjpg/1/video.mjpg`, and even `http://10.6.96.20/cgi-bin/mjpeg`) but both returned the following stack trace:

```
org.bytedeco.javacv.FrameGrabber$Exception: The camera stream ended unexpectedly
    at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:137)
    at edu.wpi.grip.core.sources.CameraSource$1.run(CameraSource.java:227)
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: The camera stream ended unexpectedly
    at edu.wpi.grip.core.sources.IPCameraFrameGrabber.readImage(IPCameraFrameGrabber.java:177)
    at edu.wpi.grip.core.sources.IPCameraFrameGrabber.grab(IPCameraFrameGrabber.java:130)
    ... 4 more
```

I'm not sure why both times GRIP failed to load the video stream as they work perfectly fine in a browser. Some things I've tried include disabling my firewall/antivirus and disabling logins on both the cameras.

Any help would be appreciated.

**UPDATE**
Still not working. Tried putting admin username and password in the URL as so: `http://admin:12345@10.6.96.10/cgi-bin/mjpeg`. It shouldn't require a username and pass though since I've tried disabling user, host, and system based authentication in the camera and I don't need it when connecting to the camera within a browser.

It also fails to even open the stream with the new radio. Please let me know if you have any idea what the issue what might be.

**Comment by cyberx696** [comment]
I was wondering if anyone else is having this issue. It's towards the end of build season and I'd like to be able to use GRIP, but I need to know whether it's going to work or not very soon. 

Thanks

**Comment by JLLeitschuh** [comment]
For the axis camera try just using the address: `http://10.6.96.10` and see if that works.

**Comment by JLLeitschuh** [comment]
If that doesn't work then there is a release candidate that may work.
https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.3.0-rc1

**Comment by cyberx696** [comment]
@JLLeitschuh 

I got the Axis working, thanks. But do you know why I can't get the Panasonic VP104 cam from working? I can view it without any authentication at http://10.6.96.10/cgi-bin/mjpeg. But when I paste that exact URL into GRIP, it crashes. I also tried just the IP in GRIP, but that doesn't work either. With the Panasonic, it requires the install of some viewer software before use.  I suspect that it may be causing issues with GRIP, but I can't be sure. 

Any help would be appreciated.

**Comment by JLLeitschuh** [comment]
It seems that the panasonic cameras need to have each frame requested. Unlike cameras that simply supporting mjpg streams.
Does this camera work with smart dashboard?

**Comment by cyberx696** [comment]
@JLLeitschuh 

No, when I add the IP in the SmartDashboard, it does not work. It does have a mjpg stream that I can view at IP/cgi-bin/mjpeg, but I cannot open it up that way in GRIP. Given that it works in a web browser, is there anything that I can do to open it in GRIP? (By the way, I am able to get it working with a generic OpenCV video program).

**Comment by JLLeitschuh** [comment]
The best thing I can tell you to do is download the GRIP source code and try to figure out why your IP address isn't working. Use the debugger, see what the http message returned actually looks like and see if IP frame grabber is parsing it wrong.

Sorry, thats probably not the answer you want to hear.

**Comment by AustinShalit** [comment]
I am going to close this issue because it has grown stale.  Please reopen this issue if you still have questions or have new information to provide.
