### ISSUE TITLE
ContoursReport prior to publishing

### ISSUE THREAD

**Issue by derekhohos** [WPIRoboticsProjects/GRIP#507]
I'm not sure if this already exists, but is there a way to see the area, centerX, centerY, width, height, and solidity values on GRIP itself instead of deploying to the robot and publishing it to NetworkTables? Currently, I'm running GRIP and an Axis camera through a laptop so I want to know if this is possible for simplicity's sake. Thanks!

**Comment by ThomasJClark** [comment]
[Yeah, using OutlineViewer](https://github.com/WPIRoboticsProjects/GRIP/wiki/Tutorial:-Deploy-to-the-Robot#previewing-networktables-values)

**Comment by derekhohos** [comment]
I see. Thank you, that helps a lot.
