### ISSUE TITLE
Running GRIP within same JVM as FRC User Program

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#526]
**Warning to any teams running across this code. This doesn't work at the moment.**

So I tried this bit of code:
```java
@Override
protected void robotInit() {
	new Thread(() -> {
		final File f = new File("/home/lvuser/grip.jar");
		try {
			URLClassLoader child = new URLClassLoader (new URL[] { f.toURI().toURL()}, this.getClass().getClassLoader());
			Class classToLoad = Class.forName ("edu.wpi.grip.core.Main", true, child);
        	Method method = classToLoad.getDeclaredMethod ("main", String[].class);
        	Object result = method.invoke (null, new Object[] {new String[]{"/home/lvuser/project.grip"}});
		} catch (MalformedURLException | ClassNotFoundException | NoSuchMethodException | InvocationTargetException | IllegalAccessException e) {
			throw new AssertionError("Failed to launch GRIP", e);
		}	
	}, "GRIP Thread").start();
	
}
```

It does launch successfully, but there are two problems.

1. We effectively take over the default thread handler for the entire JVM which means that if any threads die our handler will run instead of whatever someone has defined for the FRC User Program.
2. Network Tables tries to connect as a client instead of as a server meaning that it can't connect as it's in the same process.

Also, the FRC user program is now even larger.
```
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
15790 15787 lvuser   S     225m  92%  78% /usr/local/frc/JRE/bin/java -jar /home/lvuser/FRCUserProgram.jar
```

**Comment by ThomasJClark** [comment]
> We effectively take over the default thread handler for the entire JVM which means that if any threads die our handler will run instead of whatever someone has defined for the FRC User Program.

AFAIK wpilib doesn't set a default exception handler.  It should be fine if we override it, as long as exceptions ultimately get logged.

> Network Tables tries to connect as a client instead of as a server meaning that it can't connect as it's in the same process.

Maybe if networktables is already connected when we start up, we can just not try to do any additional configuration.

**Comment by JLLeitschuh** [comment]
> AFAIK wpilib doesn't set a default exception handler. It should be fine if we override it, as long as exceptions ultimately get logged.

Our handler intentionally stops the entire JVM in some circumstances.

**Comment by ZeusChops** [comment]
The 'best' fix is removing "-XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError" on deploy that way the crash is only handled within GRIP instead of the entire JVM.

**Comment by JLLeitschuh** [comment]
That won't fix the problem.

**Comment by ThomasJClark** [comment]
I guess you could just do `Thread.setDefaultUncaughtExceptionHandler(() -> {});` after loading GRIP.

**Comment by JLLeitschuh** [comment]
Yea, that would work.
Or just pass it null.

**Comment by AustinShalit** [comment]
We should put this in the Wiki article.

**Comment by SamCarlberg** [comment]
This isn't needed any more since code generation has been merged.
