### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by cpapplefamily** [WPIRoboticsProjects/GRIP#533]
Is there a way to rotate the Image 90deg in grip before publishing to the SmartDashboard? We have our camera mounted sideways and would like to see the SmartDashboard image correctly.

**Comment by ThomasJClark** [comment]
This looks like it works.  Change the flip to `X_AXIS` to rotate the other way.

![preview](https://cloud.githubusercontent.com/assets/3964980/13467295/a0f4b356-e06b-11e5-85ed-f06c5a6af4c2.png)
![steps](https://cloud.githubusercontent.com/assets/3964980/13467296/a20274fe-e06b-11e5-8a0c-b7e74589903f.png)

**Comment by AustinShalit** [comment]
@cpapplefamily Has this issue been solved? If so, please close this issue.

**Comment by cpapplefamily** [comment]
Leave a comment
