### ISSUE TITLE
What are the chances of a new Windows release in the near future?

### ISSUE THREAD

**Issue by jkoehring** [WPIRoboticsProjects/GRIP#537]
I have an IP camera that I would like to use with GRIP running on the Driver Station but it requires the "Content-Length" case insensitivity fix that was made to IPCameraFrameGrabber 5 days ago. It would be really convenient if I could just install a Windows release on the Driver Station instead of having to set up a GRIP build environment on the DS that would allow me to build and run GRIP on the DS. Thanks for your consideration.

**Comment by ThomasJClark** [comment]
Sure, I'll put together a new release candidate right now.

**Comment by ThomasJClark** [comment]
https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.3.0-rc2
