### ISSUE TITLE
0 contours found: Max Vertices Problem

### ISSUE THREAD

**Issue by balloman** [WPIRoboticsProjects/GRIP#538]
I am going through the tutorial for the 2016 game, but when I get to the step where I have to filter contours, I get 0 results each time, no matter what the values I put in there. I even put in 1 as the minimum area and still got nothing

**Comment by bradamiller** [comment]
The sample programs in screensteps and the wiki are based on the set of images taken before kickoff with our camera and ring light. The color of your ring light, camera settings, and lens focal length will change the parameters you need to detect goals.

**Comment by balloman** [comment]
I am using those images, but I ended up reverting to the latest release instead of using the pre-release, and that fixed the problem

**Comment by JLLeitschuh** [comment]
Can you send us an example picture and your save. Perhaps this is a bug that we can fix.

**Comment by randomtestfive** [comment]
I'm having this problem too. This is using the default filter contour settings
![gripissue](https://cloud.githubusercontent.com/assets/10055034/13764484/049a6e28-ea26-11e5-92c3-195da6e30242.png)

**Comment by ThomasJClark** [comment]
What version of GRIP? 

Can you post a screenshot of the entire filter step? (just to make sure the defaults are really what we think)

**Comment by randomtestfive** [comment]
![gripfilter](https://cloud.githubusercontent.com/assets/10055034/13764781/7942c330-ea29-11e5-8ab9-4aabdba9246f.png)

**Comment by balloman** [comment]
This seems to only happen on the pre-release as the latest release has no problem

**Comment by Sam-Carlberg** [comment]
It's a bug with Max Vertices. Seems like that's defaulting to zero (or some other small number) instead of the number in the box. Just changing that number will make it work.

**Comment by JLLeitschuh** [comment]
I wonder what's causing the bug in `Max Vertices` is.

**Comment by Sam-Carlberg** [comment]
Yeah, it's defaulting to 0. Should either just set it to 1,000,000 or put checks in the builder to set the initial value to `low` or `high` if it's out of bounds.

**Comment by ryannazaretian** [comment]
Can also confirm that I had this issue this weekend when testing GRIP. Version 1.3 RC2

**Comment by JLLeitschuh** [comment]
This should be fixed in the newest release.
