### ISSUE TITLE
Java/GRIP throws SIGSEGV with jpeg_fill_bit_buffer in libopencv_imgcodecs.so.3.0 on Raspberry Pi 2

### ISSUE THREAD

**Issue by ryannazaretian** [WPIRoboticsProjects/GRIP#544]
Commented on a closed issue (#515) two weeks ago, not sure if anyone was going to respond...

Tried with both GRIP 1.2 and 1.3. (SIGSEGV with jpeg_fill_bit_buffer in libopencv_imgcodecs.so.3.0)

[hs_err_pid958.log.txt](https://github.com/WPIRoboticsProjects/GRIP/files/174470/hs_err_pid958.log.txt)

[project.grip.txt](https://github.com/WPIRoboticsProjects/GRIP/files/174471/project.grip.txt)

Here's a link to the setup script on how I setup the Raspberry Pi environment.
https://github.com/GarnetSquardon4901/rpi-vision-processing

**Comment by EdWard680** [comment]
Is it happening for all projects or only when you run a certain operation. Whenever I try to run your project the current version of the UI just spams endless FrameGrabber related exceptions

**Comment by ryannazaretian** [comment]
It was happening for two different projects. One was a project we started back in January. Had the issue and decided to rewrite it, but still the same issue.

**Comment by rlee287** [comment]
Have you set the image size to 320x240 with 15 fps yet? If you haven't done so, I would recommend trying that to see if it helps.

**Comment by ryannazaretian** [comment]
We do. Here's our mjpg_streamer script: 
`env LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH mjpg_streamer -o "output_http.so -w ./www -p 1180" -i "input_raspicam.so -fps 15 -x 320 -y 240" &`

Regardless, GRIP should lag if I gave it too much data to process, not crash.

**Comment by ZeusChops** [comment]
Looking into the issue - there may be a connection between the heap size and this error being thrown.
