### ISSUE TITLE
Error in Java code (commit 2793ffa)

### ISSUE THREAD

**Issue by rlee287** [WPIRoboticsProjects/GRIP#562]
```java
    @AutoValue
    public static abstract class Contour {
        static Contour create(double area, double centerX, double centerY, double width, double height, double solidity) {
            return new AutoValue_ContoursReport_Contour(area, centerX, centerY, width, height, solidity);
        }
```

AutoValue_ContoursReport_Contour cannot be resolved to a type	ContoursReport.java	/core/src/main/java/edu/wpi/grip/core/operations/composite	line 56	Java Problem

This is probably Eclipse bugging out, but just thought I would point this out anyway.

**Comment by SamCarlberg** [comment]
Enable annotation processing in Eclipse

**Comment by AustinShalit** [comment]
@rlee287 Has this issue been solved? If so, please close this issue. If not, please let us know how we can help.

**Comment by rlee287** [comment]
Never got around to trying SamCarlberg's advice. I don't know what \*.jar to use as an annotation processor, but looks like our team won't be using GRIP anymore, anyway :disappointed: . I will simply close the issue for now and reopen it if our team decides to use GRIP for next year.

**Comment by JLLeitschuh** [comment]
If you have feedback regarding why your team chose not to utilize GRIP I'd love any feedback you may have.

**Comment by rlee287** [comment]
@JLLeitschuh This is not because of any flaw in the GRIP program, but rather because my team switched to a defensive strategy and chose not to utilize vision anymore.

**Comment by JLLeitschuh** [comment]
Thats unfortunate. Hopefully you'll be back next year.

GRIP will still be here!
