### ISSUE TITLE
New Release (Candidate) Build?

### ISSUE THREAD

**Issue by jkoehring** [WPIRoboticsProjects/GRIP#563]
It looks like lots of good changes have been made since the last Release Candidate build a month ago. Is there any chance of a new Release (Candidate) Build in the near future? Thanks!

**Comment by JLLeitschuh** [comment]
I've been thinking about this for the past couple of days. I'll try to get a new release out this week.

**Comment by jkoehring** [comment]
That would be great. Thanks!-- john

**Comment by JLLeitschuh** [comment]
[Released](https://github.com/WPIRoboticsProjects/GRIP/releases/tag/v1.4.0)
Thanks!
