### ISSUE TITLE
Build x86 windows releases with AppVeyor

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#612]
This may be as easy as setting an environment variable in the build script in AppVeyor.
This would be great if anyone wanted to take a look.

**Comment by AustinShalit** [comment]
platform:
  - x86

**Comment by JLLeitschuh** [comment]
That doesn't work. Already tried it. It still uses x64 machine to build the env.

**Comment by SamCarlberg** [comment]
How about `i386`?

**Comment by JLLeitschuh** [comment]
Is that something that appveyor accepts as an argument?

**Comment by SamCarlberg** [comment]
Nope. Thought it might have been.

This might work, though. See https://www.appveyor.com/docs/appveyor-yml lines 163-169

```
platform:
  - x86
  - x64
```

**Comment by SamCarlberg** [comment]
All artifacts are now built on Azure (#903), including 32-bit windows
