### ISSUE TITLE
Forbid string "(non-Javadoc)" in comments.

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#614]
I really dislike the eclipse `(non-Javadoc)` comments that eclipse tends to generate.
We can probably do this with checkstyle.

**Comment by AustinShalit** [comment]
This can also be used to check for ```System.out.println()``` calls

**Comment by JLLeitschuh** [comment]
Yea, but make sure that there is a documented way to disable it if you want to run code that needs to print line for debugging purposes.
