### ISSUE TITLE
Add Findbugs To build

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#615]
We should add findbugs to help keeping us from shooting ourselves in the foot.
https://docs.gradle.org/current/userguide/findbugs_plugin.html

**Comment by AustinShalit** [comment]
Findbugs does not have a console output option.  Can we have travis expose the report file findbugs generates?

**Comment by JLLeitschuh** [comment]
Give something like this a shot: http://stackoverflow.com/a/28098325/3708426
