### ISSUE TITLE
GRIP cron task to deploy

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#622]
We should probably add the option to create a cron task for grip on deploy.

**Comment by JLLeitschuh** [comment]
Cron task?

**Comment by SamCarlberg** [comment]
Linux cron job to run GRIP, probably on boot, if it's been deployed. Besically [this](http://stackoverflow.com/questions/5034333/creating-cron-entry-on-server-using-ssh-login-within-shell-script)

**Comment by SamCarlberg** [comment]
Do we still need this? I feel like the deploy mechanism is superfluous now that we have code generation

**Comment by JLLeitschuh** [comment]
I think its still relevant.
Unless you can deploy code gen like you can deploy GRIP I think deployment makes sense to keep in GRIP.

**Comment by SamCarlberg** [comment]
You can generate code in a robot program directory and deploy that like a normal FRC program. Or save it to another project directory and FTP it/copy on a flashdrive to a raspberry pi or jetson or kangaroo or...

**Comment by JLLeitschuh** [comment]
Yea, but that doesn't include sources/network tables publishing.

**Comment by SamCarlberg** [comment]
Right, they'd have to add that code themselves. Again, we should do a survey on the use of deploy vs code gen during/after the 2017 season

**Comment by JLLeitschuh** [comment]
Sure.
