### ISSUE TITLE
Close old issues

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#625]
I think we can close these issues either because they have been solved or are stale:

 ~~#245~~
~~#261~~ 
~~#290~~ 
~~#354~~ 
~~#357~~ 
~~#370~~
#374
#391
#407
#413

~~#441~~ 
~~#465~~ 
~~#467~~ 
~~#473~~ 
#494
#500

~~#503~~ 
~~#526~~ 
~~#528~~ 
~~#533~~

**Comment by AustinShalit** [comment]
@JLLeitschuh Thoughts?

**Comment by ZeusChops** [comment]
Double check #543 as well, I just tried that and didn't have issues. (I'm running macOS Sierra beta 1 right now, so a check on El Capitan would be nice.)
