### ISSUE TITLE
⌘Q -> Cancel still quits GRIP

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#660]
Using the shortcut ⌘Q and pressing cancel on the dialog still quits GRIP when it should just close the dialog.

**Comment by ZeusChops** [comment]
This happens sometimes. I've just ran GRIP ten times and tried the steps found in #543 and never hit a deadlock exception. To add to that thought, using [Command + Q] is macOS's shortcut for force quitting an application. Also, it shows the shortcut for the exit button in the drop-down as [Command + Q]..

Is there a video or something of this acting not as explained above?

**Comment by SamCarlberg** [comment]
See https://bugs.openjdk.java.net/browse/JDK-8117679

We'll need to refactor the confirmation dialog stuff so it can get used in an event handler for the root stage
