### ISSUE TITLE
I can No longer auto launch the Grip app and load a pipeline

### ISSUE THREAD

**Issue by cpapplefamily** [WPIRoboticsProjects/GRIP#670]
With the latest update I can no longer Auto launch the Grip app on the Kangaroo with our pipe line the shortcut is  C:\Users\apple\AppData\Local\GRIP\GRIP.exe "C:\Users\apple\Documents\FRC GRIP FILES\Test.grip"

Do I have the shortcut wrong? I did recreate the pipe line because the new version would not open the old file.

**Comment by cpapplefamily** [comment]
Reading other current issues seems this maybe in line with the issue "not launching the JVM". If I delete the file test.grip from the shortcut GRIP will launch.

**Comment by cpapplefamily** [comment]
Reading other current issues seems this maybe in line with the issue "not launching the JVM". If I delete the file test.grip from the shortcut GRIP will launch.

**Comment by cpapplefamily** [comment]
I just went back to GRIP-1.4.0-x64 and the short cut with the file parameter works. Could be something with the new launch window?

**Comment by JLLeitschuh** [comment]
@AustinShalit You know anything about this?

**Comment by AustinShalit** [comment]
I will look into this

**Comment by AustinShalit** [comment]
@cpapplefamily Thank you for finding this bug!  I will fix it tonight.  It was created in #629.

**Comment by JLLeitschuh** [comment]
What's the cause?

**Comment by AustinShalit** [comment]
Opening the pipeline before the list of operations has been created.  

https://github.com/WPIRoboticsProjects/GRIP/blob/64de5d988e0481b51ffd2058694d8ae54ec8398a/ui/src/main/java/edu/wpi/grip/ui/Main.java#L103-L123

**Comment by JLLeitschuh** [comment]
That would do it.
