### ISSUE TITLE
Can't generate code

### ISSUE THREAD

**Issue by YairZiv5951** [WPIRoboticsProjects/GRIP#684]
Please describe what actions we can take to reproduce the bug you found, including the error message.

I pressed Generate code and it threw a velocity exception.

**Comment by JLLeitschuh** [comment]
Can you upload a zip of your `.grip` save file as well as the exception you experienced?

**Comment by MoSadie** [comment]
I'm experiencing the same issue. Here is a gist of the exception: https://gist.github.com/MoSadie/f1f5a2c7808b3330b52d6d1482cac270

Here is a link to the .grip project file: https://1drv.ms/u/s!AgQZOPyu2Ulvj6lPWN-UV1b85qMq_w

**Comment by SamCarlberg** [comment]
I confirmed this happens with 1.5.0-rc2, but I'm not seeing it on the current master (54d98ea)

Can you download [the master zip](https://github.com/WPIRoboticsProjects/GRIP/archive/master.zip) and try again?

**Comment by MoSadie** [comment]
That appears to have solved the problem! Thanks!

**Comment by SamCarlberg** [comment]
Never mind. Just built that commit as a native app on Windows 10 and it still fails.
