### ISSUE TITLE
Resize not working in Ubuntu

### ISSUE THREAD

**Issue by PaulaRudy** [WPIRoboticsProjects/GRIP#69]
I can full screen and minimize but not resize the window manually. The split screen is working however.

**Comment by ThomasJClark** [comment]
I can't reproduce this as of v0.1.0 on a fresh VM with Ubuntu 15.10.  You were probably right - it's a problem with computer.

**Comment by PaulaRudy** [comment]
Still an issue here. It happens after I open a source image or  webcam, even if "cancel"ed. Before I try to add a source the resize works.

**Comment by JLLeitschuh** [comment]
Are you still experiencing this problem??

**Comment by PaulaRudy** [comment]
Yes.

**Comment by PaulaRudy** [comment]
I've been poking around with this but I'm at a loss here. Any suggestions?

**Comment by JLLeitschuh** [comment]
I think this is taken care of. I'm going to close this.
