### ISSUE TITLE
Don't crash GRIP if there is already a process bound to port 8080

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#721]
Grip should instead startup with a warning and the internal server disabled, or perhaps with a dialog that lets you pick a different port to start the server on.

**Comment by SamCarlberg** [comment]
Can't disable the server. Dialog might work. How would you handle this for the headless case?

**Comment by JLLeitschuh** [comment]
Uhh... For the headful case just shut down the server and show a warning?

**Comment by AustinShalit** [comment]
:+1: I agree that this should be fixed.

**Comment by Wazzaps** [comment]
I would recommend to assign a random unused port and use that, and show a warning that the port is used. Or have the port configurable

**Comment by SamCarlberg** [comment]
I forgot to close this one. The port's been changed to 2084 from 8080, and allows the user to continue without the HTTP functionality if the port is already in use.
