### ISSUE TITLE
GRIP not running correctly on RIO

### ISSUE THREAD

**Issue by Ubspy** [WPIRoboticsProjects/GRIP#740]
Hello, everyone! I seem to be having a problem with the NetworkTables on the roborRIO.

I have successfully deployed my code to the roboRIO, but it doesn't seem to want to run correctly for some reason. If I run the code on the roboRIO, nothing is published to the NetworkTables. Even though in the console I get: "INFO: SUCCESS! The project is running in headless mode."

If I run the GRIP code on my laptop however, it publishes fine to the NetworkTables. Do you guys know what might be the source of the problem?

**Comment by SamCarlberg** [comment]
You need to launch GRIP with the save file to run

```bash
$ /home/lvuser/bin/java -jar /path/to/grip.jar --file /path/to/save.grip
```

---

We're leaning away from the deploy function altogether in favor of generating code you can run in your robot program. It's faster, uses less memory, and is less of a headache to get working. Have you tried that instead?

**Comment by JLLeitschuh** [comment]
@Ubspy Where are you running your network tables server?

**Comment by Ubspy** [comment]
@SamCarlberg That just threw me a huge error.

@JLLeitschuh I should be running the network tables server on the roboRIO, when I use GRIP on my laptop it publishes the values correctly. But not on the RIO.

**Comment by Ubspy** [comment]
Also @SamCarlberg I was running "/usr/local/frc/JRE/bin/java -jar '/home/lvuser/grip.jar' '/home/lvuser/project.grip'" if that clarifies anything for you.

**Comment by SamCarlberg** [comment]
That command won't work. You need to use the `--file` option to specify the project file

```bash
$ /usr/local/frc/JRE/bin/java -jar /home/lvuser/grip.jar --file /home/lvuser/project.grip
```

**Comment by Ubspy** [comment]
@SamCarlberg that gives me a massive error

**Comment by SamCarlberg** [comment]
Can you post it? Preferably as a [gist](http://gist.github.com) if it's long

**Comment by Ubspy** [comment]
@SamCarlberg here's the error I got: https://gist.github.com/Ubspy/e395c7aed95ba858fc986296cc800f0d

**Comment by SamCarlberg** [comment]
Your pipeline was started, but OpenCV couldn't understand the video format ([these lines](https://gist.github.com/Ubspy/e395c7aed95ba858fc986296cc800f0d#file-grip-error-L117-L124)).

What camera are you using, and how is it connected to the roborio?

**Comment by Ubspy** [comment]
@SamCarlberg we're using the Microsoft LifeCam HD-3000, and it's connected via USB.

**Comment by SamCarlberg** [comment]
Any other USB devices plugged in?

**Comment by Ubspy** [comment]
No, just the camera.

**Comment by Ubspy** [comment]
@SamCarlberg No, just the camera.

But it seems that if I plug that camera into my laptop it works just fine. It still publishes all the values to network tables.

**Comment by Ubspy** [comment]
@SamCarlberg Is there some kind of driver I need for the camera? Because it works fine on my laptop, but the camera doesn't seem to want to start on the RIO.

**Comment by Ubspy** [comment]
Looks like the new version of GRIP isn't supposed to run on the RIO, so that solves this issue.
