### ISSUE TITLE
Python code generation tests fail on Travis

### ISSUE THREAD

**Issue by SamCarlberg** [WPIRoboticsProjects/GRIP#761]
pip can't find the `opencv-python`  package on PyPi, so the python bindings don't get installed. This isn't specific to Travis; something in pip or on the PyPi site broke. This'll be open until that package is fixed.

**Comment by JLLeitschuh** [comment]
Can you get this fixed in a way that does not reduce code coverage. Open an issue with whoever is responsible and reference this issue please.

**Comment by SamCarlberg** [comment]
No longer necessary. Code generation tests run on all the Azure VMs
