### ISSUE TITLE
Move code cov to Travis Mac Build

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#773]
The travis Mac build has higher code coverage as it runs the code generation tests.

We should move the codecov reporting over to that because the report result will be higher.

**Comment by AustinShalit** [comment]
Are you doing this or is it a PR's Please?

**Comment by JLLeitschuh** [comment]
Whoever gets to it first.

**Comment by SamCarlberg** [comment]
Obviated by #903 and #907. The Azure CI now runs all tests on all platforms, and uploads code coverage from the Linux builds
