### ISSUE TITLE
Code Generation Package does not allow pasting in

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#775]

**Comment by SamCarlberg** [comment]
Can't paste an invalid package eg `1234`. Valid packages can be pasted eg `foo.bar`

**Comment by AustinShalit** [comment]
I am trying to do `org.usfirst.frc.team190.robot`

**Comment by SamCarlberg** [comment]
Which is an invalid package name (numerals). #777 fixes that.

**Comment by AustinShalit** [comment]
Open until that gets merged

**Comment by AustinShalit** [comment]
Nevermind
