### ISSUE TITLE
C++ enums use scoped references

### ISSUE THREAD

**Issue by CadeBrown** [WPIRoboticsProjects/GRIP#780]
When code is generated for c++ (using latest release), enums (like BlurType) are referenced through a VisualStudio/Microsoft specific way.

See: [this SO post](http://stackoverflow.com/questions/5188554/my-enum-is-not-a-class-or-namespace) for an example.

Essentially, the generated code references "BlurType::Gaussian" where it should just be "Gaussian"

I'm not sure if the dev team just uses VS, but it doesn't compile with g++ (until you make the change and remove "BlurType::").

**Comment by nightpool** [comment]
This is not just a Microsoft specific extension, it was something added in
C++11. I don't know the specific status of the rest of GRIP's compatibility
with c++11, but I would recommend that you use it for your projects.
