### ISSUE TITLE
Generated code giving errors.

### ISSUE THREAD

**Issue by NonayMete** [WPIRoboticsProjects/GRIP#786]
When I bring up the generated grip code in eclipse I get a few errors, I am using GRIP 1.5.0 and c++

```
void GripPipeline::setsource0(cv::Mat &source0){
	source0.copyTo(this->source0);
}
```
this line shows up saying, Member Declaration not found.
```
class GripPipeline : public VisionPipeline { ... } 
```
the main class in the .h file gives this error: expected class-name before '{' token

 Eclipse also cannot find `<opencv2/contrib/contrib.hpp>`, despite the fact I am using wpilib 2017 and putting the .cpp and .h files in my src folder. Any help would be appreciated.

**Comment by SamCarlberg** [comment]
The generated code isn't great and has a ton of unused imports/includes. For now, you'll have to delete the unused includes like  `<opencv2/contrib/contrib.hpp>` (the contrib module isn't included on the RoboRIO).

You should also update to 1.5.1, it fixes a few other problems with code generation.

**Comment by nightpool** [comment]
duplicate of #797
