### ISSUE TITLE
about opening images

### ISSUE THREAD

**Issue by blahBlahhh** [WPIRoboticsProjects/GRIP#799]
cannot add images which are in jpg. it says that the images I selected are invalid. But I just downloaded those images from FRC.

**Comment by bradamiller** [comment]
Can you verify that you have a directory full of .jpg images of the field (not a zip file), and that you can view them without GRIP. Then follow these directions and see if it is still not working for you:

http://wpilib.screenstepslive.com/s/4485/m/24194/l/683625-processing-images-from-the-2017-frc-game

**Comment by SamCarlberg** [comment]
Closing as stale.
