### ISSUE TITLE
GRIP Code Generation Capitalization Error

### ISSUE THREAD

**Issue by 333fred** [WPIRoboticsProjects/GRIP#805]
_From @RaidingForPants on January 27, 2017 20:58_

When using the GRIP Computer Vision Pipeline to generate code, the function which overrides the virtual function "Process" in the parent class, VisionPipeline, is not capitalized, and is generated as "process".

In MyPipeline.h:
`public:
		MyPipeline();
		void process(cv::Mat source0);
		cv::Mat* gethsvThresholdOutput();
		cv::Mat* getcvDilateOutput();
`

In VisionPipeline.h:
`public:
  virtual ~VisionPipeline() = default;

  /**
   * Processes the image input and sets the result objects.
   * Implementations should make these objects accessible.
   */
  virtual void Process(cv::Mat& mat) = 0;
`

_Copied from original issue: wpilibsuite/allwpilib#473_

**Comment by SamCarlberg** [comment]
This is a known issue and I've already started working on it. See #798

**Comment by 333fred** [comment]
Dupe of https://github.com/WPIRoboticsProjects/GRIP/issues/797.
