### ISSUE TITLE
GRIP won't automatically startup with chosen grip file

### ISSUE THREAD

**Issue by MarcelPretty** [WPIRoboticsProjects/GRIP#817]
We have GRIP 1.5.2 running on a Kangaroo with a USB Microsoft LifeCam HD camera plugged in.  (Same issue below happens with 1.5.1)

GRIP runs fine when launched and we can File->Open our grip file, however when setting GRIP to auto-start with our grip file as a parameter (i.e. C:\USERS\1305\AppData\Local\GRIP\GRIP.exe "C:\FRC\goal.grip") it will open GRIP but not open the file, and the bottom of the screen says "Pipeline stopped. Did not run" and none of the grip file is loaded.  Going to File->Open and manually selected the file works fine though.

Marcel Pretty
Team 254

**Comment by SamCarlberg** [comment]
Please read [the wiki page on running GRIP from the command line](https://github.com/WPIRoboticsProjects/GRIP/wiki/Command-line-options)

**Comment by MarcelPretty** [comment]
Thank you!!
