### ISSUE TITLE
Error setting up build tools

### ISSUE THREAD

**Issue by ajbt200128** [WPIRoboticsProjects/GRIP#846]
When setting up build tools there are 2 problems I run into. 

1. maven says there are unindexed remote maven repositiries found, and when I try to update them(http://first.wpi.edu/FRC/roborio/maven/development and http://first.wpi.edu/FRC/roborio/maven/release) it gives an error saying "nexus-maven-repository-index.properties does not exist". 
2. When I try to build it gives errors saying packages "edu.wpi.grip.generated.opencv_core.enumeration.CmpTypesEnum" and others of the same type do not exist

**Comment by JLLeitschuh** [comment]
Is this in intellij?
The unindexed remote maven repositories problem is not really a problem just a warning. It can be safely ignored.

**Comment by ajbt200128** [comment]
The error still persists even after running `./gradlew generateCodeFromSource`. This is in intellij, also in the gradle projects window there are errors which say "unable to resolve ..." for NetworkTables, OpenCV, rosjava, and grip_msgs. Could me being on windows have anything to do with it?

**Comment by JLLeitschuh** [comment]
@SamCarlberg Have you seen this before??

**Comment by SamCarlberg** [comment]
I haven't seen this before. Just running `./gradlew :ui:run` (or `gradlew.bat :ui:run` in this case) from a fresh clone should work as long as you have an internet connection

**Comment by ajbt200128** [comment]
I can build the gradle project but the problem is if I try to edit any code it will tell me that there are unresolved symbols with the openv library imports, and in the gradle window under :ui/Source Sets/main/Dependencies it says those libraries cannot be resolved
