### ISSUE TITLE
Does not correctly build on Windows

### ISSUE THREAD

**Issue by ThadHouse** [WPIRoboticsProjects/GRIP#857]
The LinuxLauncher project is always included and being built, but does not correctly build on windows. This project should be only be enabled on linux builds.

**Comment by AustinShalit** [comment]
What gradle task are you running?

**Comment by ThadHouse** [comment]
Gradlew build

**Comment by JLLeitschuh** [comment]
So on appveyor we run the `jfxNative` task to build the installer.

**Comment by ThadHouse** [comment]
I'm sure there is a good task for it, but `gradlew build` should not just outright fail on windows.

**Comment by ThadHouse** [comment]
This has been fixed as of 8923d10277f2ccd31621154e4c46ea5afa4238f4
