### ISSUE TITLE
Build GRIP with Docker on TravisCI

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#867]
This requires setting up the build to use the same build logic as [shuffleboard](https://github.com/wpilibsuite/shuffleboard). This will be slightly more complicated as we also need to extract build artifacts out of the docker container for releases.

**Comment by SamCarlberg** [comment]
No longer needed since we're using Azure pipelines to do our builds (as is Shuffleboard now)
