### ISSUE TITLE
Network Tables 4.0

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#869]
We need update GRIP to using the newest version of Network Tables once it is out of beta.

[View this Epic with Zenhub](https://app.zenhub.com/)

**Comment by SamCarlberg** [comment]
Seems like this and #868 are the same thing. And why does this need a third-party service to track? A single issue is enough. This is a straightforward upgrade to make.

**Comment by JLLeitschuh** [comment]
I've been using ZenHub off and on for GRIP since this was my MQP. If you look at the epic it actually has the two issues under it.
