### ISSUE TITLE
Incorrect code generated regarding contours with opencv

### ISSUE THREAD

**Issue by pirates1010** [WPIRoboticsProjects/GRIP#870]
When using contours, the generated python code in  `def __find_contours(input, external_only): `function has an error. The line right before return contours is 
`im2, contours, hierarchy =cv2.findContours(input, mode=mode, method=method)`
but should be  `contours, hierarchy =cv2.findContours(input, mode=mode, method=method) `to avoid an error.  This is with python 2 and opencv 2.4.9.  This was carried out on a jetson tx1.

**Comment by twinters007** [comment]
The 'incorrect' code is for opencv 3, not 2.

**Comment by SamCarlberg** [comment]
Yes, the generated code targets Python 3 and OpenCV 3

**Comment by pirates1010** [comment]
Ah, this now makes sense, thanks.
