### ISSUE TITLE
Building on macOS fails after first build

### ISSUE THREAD

**Issue by twinters007** [WPIRoboticsProjects/GRIP#873]
`./gradlew :ui:run` 

Everything works, app loads, etc
> Quit

`./gradlew :ui:run`
```
error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Error reading configuration file
1 error
:ui:compileJava FAILED
```

**Comment by bradamiller** [comment]
Do you already have a copy of grip running when starting the new one?

-- 
Brad Miller

**Comment by twinters007** [comment]
I didn't before, yet it's working now. Maybe intellij had a background process? Idk

**Comment by twinters007** [comment]
I'm gonna close this then until it happens again. Thanks Brad

**Comment by SamCarlberg** [comment]
@JLLeitschuh can you test this?
