### ISSUE TITLE
FindBugs -> SpotBugs

### ISSUE THREAD

**Issue by AustinShalit** [WPIRoboticsProjects/GRIP#886]
FindBugs is dead and has been replaced with SpotBugs.

More information available in this email: https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2017-September/004383.html

**Comment by JLLeitschuh** [comment]
Go for it.
I've been debating replacing Findbugs at Plexxi as well.

**Comment by SamCarlberg** [comment]
Closed by #900
