### ISSUE TITLE
How do I run GRIP from VS Code?

### ISSUE THREAD

**Issue by npetrangelo** [WPIRoboticsProjects/GRIP#896]
I made a fork of GRIP and I want to try adding some stuff, but I'm more familiar with Eclipse and I'm completely lost in VS Code and Gradle. I haven't made any changes yet, I'm just looking to run the program as is first to make sure I've installed everything correctly.

**Comment by SamCarlberg** [comment]
You can't. GRIP is a standalone program. Downloads are available on the releases page: https://github.com/WPIRoboticsProjects/GRIP/releases
