### ISSUE TITLE
Find Lines generated code in Python skips first line

### ISSUE THREAD

**Issue by GrantPerkins** [WPIRoboticsProjects/GRIP#908]
Generated Python code on version 1.5.2 in ___find_lines(input) does not return the first line.

Generated code:
` for i in range(1, len(lines[0])):`

Fix:
` for i in range(0, len(lines[0])):`

**Comment by calcmogul** [comment]
The first argument to range() can be omitted for starting values of zero.

**Comment by GrantPerkins** [comment]
Yes, that's true. We were still debugging when I opened this, and was uncertain if I wanted to start at 0 or not for a reason unrelated to the issue.
