### ISSUE TITLE
GRIP closes when more than 1 IP cameras are added

### ISSUE THREAD

**Issue by anon-raizer** [WPIRoboticsProjects/GRIP#918]
After adding a 2nd or 3rd IP camera, grip closes all by itself, but if I only use 1 IP camera it works fine.

**Comment by JLLeitschuh** [comment]
Is there a log/exception you can share with us?

**Comment by JLLeitschuh** [comment]
@SamCarlberg If you get a second, can you test this?

**Comment by SamCarlberg** [comment]
Cannot reproduce locally. Closing since no further information is forthcoming.
