### ISSUE TITLE
Switch statements should have a default label

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#94]
#### Occurred on:
+ **Commit**:  ed3e9ee537ae38068da780ba4516df557d691d64
+ **File**:    [src/main/java/edu/wpi/grip/ui/util/ImageConverter.java](https://github.com/WPIRoboticsProjects/GRIP/blob/ed3e9ee537ae38068da780ba4516df557d691d64/src/main/java/edu/wpi/grip/ui/util/ImageConverter.java)
+ **LineNum**: [60](https://github.com/WPIRoboticsProjects/GRIP/blob/ed3e9ee537ae38068da780ba4516df557d691d64/src/main/java/edu/wpi/grip/ui/util/ImageConverter.java#L60)
+ **Code**:    `        switch (channels) {`

    
#### Currently on:
+ **Commit**:  c0df380eb03f3598af4e3ace2d56d58b1613c6f0
+ **File**:    [src/main/java/edu/wpi/grip/ui/util/ImageConverter.java](https://github.com/WPIRoboticsProjects/GRIP/blob/c0df380eb03f3598af4e3ace2d56d58b1613c6f0/src/main/java/edu/wpi/grip/ui/util/ImageConverter.java)
+ **LineNum**: [60](https://github.com/WPIRoboticsProjects/GRIP/blob/c0df380eb03f3598af4e3ace2d56d58b1613c6f0/src/main/java/edu/wpi/grip/ui/util/ImageConverter.java#L60)

**Comment by ThomasJClark** [comment]
@JLLeitschuh, turn off this codacy thing

**Comment by JLLeitschuh** [comment]
Did you resolve this issue?

**Comment by ThomasJClark** [comment]
This isn't an issue

https://github.com/WPIRoboticsProjects/GRIP/blob/ed3e9ee537ae38068da780ba4516df557d691d64/src/main/java/edu/wpi/grip/ui/util/ImageConverter.java#L38

**Comment by JLLeitschuh** [comment]
Assertions are turned off in the full version of the code.

**Comment by JLLeitschuh** [comment]
Had I seen this I wouldn't have approved the PR.
That won't happen again thanks to codacity.
