### ISSUE TITLE
Installed through .deb on Ubuntu, name to run lost?

### ISSUE THREAD

**Issue by ColeScheller** [WPIRoboticsProjects/GRIP#947]
Really quick one (I hope). I installed the .deb using sudo dpkg -i gripfile.deb. It goes through the install properly, no errors, and then I can't run it. Normally this would give me the ability to just type in the name in a terminal and it runs, but for some reason it's not named grip. I have no idea what it is named and I can't run it if I don't know that.

**Comment by PeterJohnson** [comment]
The command is not put on the path, it's installed to /opt/grip/GRIP.

**Comment by ColeScheller** [comment]
That fixed it, thanks!
