### ISSUE TITLE
LineSegmentDetector Removed from OpenCV(4.1.0)

### ISSUE THREAD

**Issue by hamzaMahdi** [WPIRoboticsProjects/GRIP#951]
When using the LineSegmentDetector function (generated by the Find Lines block), building with opencv 4 fails because the function was removed due to original code license issues in function 'LineSegmentDetectorImpl'

Here is the output:
`libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.1.0) /tmp/opencv-20190505-12101-14vk1fh/opencv-4.1.0/modules/imgproc/src/lsd.cpp:143: error: (-213:The function/feature is not implemented) Implementation has been removed due original code license issues in function 'LineSegmentDetectorImpl'`

**Comment by AustinShalit** [comment]
OpenCV 4 is not currently supported.  We will keep this in mind when we upgrade.
