### ISSUE TITLE
Line filter Issues

### ISSUE THREAD

**Issue by JLLeitschuh** [WPIRoboticsProjects/GRIP#97]
Line Filter should take a minimum and a maximum.
It should indicate what the length's scale is, or alternatively it should be relative to the size of the mat so it doesn't matter if the resize operation changes.

**Comment by ThomasJClark** [comment]
There is no scaling done in Line Filter, it just filters based on the raw length of a line

What use case would having a maximum line length help?

**Comment by JLLeitschuh** [comment]
Raw length in what? Pixels?

**Comment by ThomasJClark** [comment]
yes
