### ISSUE TITLE
Grip Mac install is damaged

### ISSUE THREAD

**Issue by srajanpm** [WPIRoboticsProjects/GRIP#973]
Trying to install Grip(v1.6.0 Release candidate 4) on Mac (MAC OS version Catalina 10.15.5). 
It seems to install successfully but trying to run it errors out with the following error:

"GRIP" is damaged and can't be opened. You should eject the disk image.

What Mac OS version does v1.6.0 release candidate support?
Thanks for the help!

**Comment by AustinShalit** [comment]
Hi @srajanpm. Can you please try to use a released version rather than a release candidate?

**Comment by srajanpm** [comment]
> Hi @srajanpm. Can you please try to use a released version rather than a release candidate?

yes thanks. release 1.5.2 v works.
